Repository nextcloud/polls, pull requests merged in 2018-11, with the labels that each got.

#427 Remove italic styling for winner entries, bold is enough
  css/vote.scss
Labels: 3. to review, bug, design

#423 Use the email templating and use the language of the recipient
  lib/AppInfo/Application.php
  lib/Controller/PageController.php
  tests/Unit/Controller/PageControllerTest.php
Labels: enhancement, translation

#422 Allow Nextcloud 15
  appinfo/info.xml
Labels: 3. to review, enhancement

#432 Load options html decoded
  lib/Controller/ApiController.php
Labels: bug
