Repository nextcloud/polls, pull requests merged in 2018-12, with the labels that each got.

#437 Disallow to allow
  css/colors.scss
  css/vote.scss
  img/maybe-vote-variant.svg
  js/create-poll.js
  js/vote.js
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Db/Event.php
  lib/Migration/Version0009Date20181125061900.php
  src/js/Create.vue
  templates/vote.tmpl.php
Labels: 3. to review, enhancement

#440 Update max-version to current dev version 16
  appinfo/info.xml
Labels: 3. to review, server

#451 fix link to create poll on empty main site
  templates/main.tmpl.php
Labels: bug

#456 Migration fix 2
  appinfo/info.xml
  lib/Migration/Version0009Date20181125051900.php
  lib/Migration/Version0009Date20181125061900.php
Labels: bug

#465 Refactor api controller
  appinfo/routes.php
  js/start.js
  js/vote.js
  lib/AppInfo/Application.php
  lib/Controller/ApiController.php
  lib/Controller/PageController.php
  lib/Controller/SystemController.php
  lib/Db/EventMapper.php
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/Vote.php
  lib/Db/VoteMapper.php
  lib/Migration/Version0009Date20181125061900.php
  package.json
  templates/vote.tmpl.php
  tests/Unit/Controller/PageControllerTest.php
  tests/Unit/Db/OptionMapperTest.php
  tests/Unit/Db/VoteMapperTest.php
  tests/Unit/Factories/OptionFactory.php
  tests/Unit/Factories/VoteFactory.php
Labels: 3. to review
