Repository nextcloud/polls, pull requests merged in 2020-03, with the labels that each got.

#842 Dependency and config tidy
  .babelrc.js
  .eslintrc.js
  lib/Model/Acl.php
  package.json
  src/js/components/Share/ShareDiv.vue
  src/js/main.js
  src/js/store/modules/poll.js
  src/js/views/PollList.vue
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 4. to release

#854 Remove users from a poll
  appinfo/routes.php
  lib/Controller/VoteController.php
  src/js/components/Base/UserDiv.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/store/modules/votes.js
Labels: 4. to release, enhancement

#857 Add login link in public votes
  src/js/components/VoteTable/VoteHeaderPublic.vue
Labels: 3. to review, enhancement

#823 Delete poll permanently
  appinfo/routes.php
  lib/Controller/PollController.php
  lib/Migration/Version0104Date20200205104800.php
  src/js/components/Navigation/Navigation.vue
  src/js/components/Navigation/PollNavigationItems.vue
  src/js/components/PollList/PollListItem.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/store/modules/polls.js
Labels: 4. to release

#875 Share poll via email #822
  lib/Controller/PollController.php
  lib/Controller/ShareController.php
  lib/Controller/SystemController.php
  lib/Controller/VoteController.php
  lib/Model/Acl.php
  lib/Service/MailService.php
  src/js/components/Base/UserDiv.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
  src/js/store/modules/shares.js
  src/js/views/Vote.vue
Labels: 4. to release
