Repository nextcloud/polls, pull requests merged in 2020-02, with the labels that each got.

#839 workaround for #830
  src/js/components/SideBar/SideBarTabConfiguration.vue
Labels: 4. to release

#837 Empty description
  lib/Controller/PollController.php
  lib/Db/Poll.php
  lib/Model/Acl.php
  src/js/components/Base/PollDescription.vue
  src/js/components/PollList/PollListItem.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/store/modules/poll.js
Labels: 4. to release

#838 fixes setting admin rights, disable fullAnonymous
  lib/Controller/PollController.php
  lib/Db/Poll.php
  lib/Model/Acl.php
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/store/modules/poll.js
Labels: 3. to review

#840 fix #809
  src/js/components/SideBar/SideBarTabOptionsDate.vue
Labels: 4. to release

#843 Pinned navigationItem "Deleted polls"
  src/js/components/Navigation/Navigation.vue
Labels: 4. to release, UX, design

#835 removed duplicate question for cloud version
  .github/ISSUE_TEMPLATE/bug_report.md
  ISSUE_TEMPLATE.md
Labels: 4. to release

#846 Public link cursor and Autofocus name field in public vote
  src/js/components/Base/ButtonDiv.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/SideBar/SideBarTabOptionsDate.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
  src/js/main.js
  src/js/views/Vote.vue
Labels: 4. to release

#845 workaround darkReader (browser add-on)
  src/js/App.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
Labels: 3. to review

#844 fix #841 - changed vote icons
  src/js/components/VoteTable/VoteTableItem.vue
Labels: 4. to release, UX

#848 Button style
  src/js/components/Base/ButtonDiv.vue
  src/js/components/Navigation/Navigation.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/SideBar/SideBarTabOptionsDate.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
  src/js/views/Vote.vue
Labels: 3. to review, UX, design
