Repository nextcloud/polls, pull requests merged in 2020-01, with the labels that each got.

#724 Fix comments
  lib/Controller/CommentController.php
  lib/Controller/SystemController.php
  lib/Service/MailService.php
  src/js/components/Comments/CommentAdd.vue
  src/js/views/PollList.vue
Labels: 3. to review

#730 use submit event of form to add a comment
  src/js/components/Comments/CommentAdd.vue
Labels: 4. to release

#753 Sort polls in poll list
  src/js/components/Comments/Comments.vue
  src/js/components/PollList/PollListItem.vue
  src/js/store/modules/comments.js
  src/js/views/PollList.vue
Labels: 3. to review, design, enhancement

#785 routing optimizations
  appinfo/routes.php
  lib/Controller/PageController.php
Labels: enhancement

#783 Allow site user to vote in hidden poll via public link #779
  lib/Model/Acl.php
  src/js/store/modules/acl.js
  src/js/views/PublicVote.vue
Labels: bug
