Repository nextcloud/polls, pull requests merged in 2020-04, with the labels that each got.

#874 Keep the user anonymous #871
  lib/Service/MailService.php
Labels: 4. to release, bug

#870 Avoid double loading of poll list
  lib/Controller/PollController.php
  src/js/App.vue
  src/js/components/Create/CreateDlg.vue
  src/js/components/Navigation/Navigation.vue
  src/js/components/PollList/PollListItem.vue
  src/js/components/Subscription/Subscription.vue
  src/js/views/PollList.vue
  src/js/views/Vote.vue
Labels: 4. to release

#877 force options order by timestamp in date polls
  lib/Controller/OptionController.php
  lib/Db/Option.php
Labels: 4. to release, bug

#876 Poll filters
  src/js/App.vue
  src/js/components/Base/PollDescription.vue
  src/js/components/Base/PollTitle.vue
  src/js/components/Navigation/Navigation.vue
  src/js/components/PollList/PollListItem.vue
  src/js/router.js
  src/js/store/modules/polls.js
  src/js/views/PollList.vue
  src/js/views/Vote.vue
Labels: 4. to release, UX, enhancement

#884 Design issues
  src/js/App.vue
  src/js/components/Base/PollItemDate.vue
  src/js/components/Base/PollItemText.vue
  src/js/components/Base/UserDiv.vue
  src/js/components/Comments/CommentAdd.vue
  src/js/components/Navigation/Navigation.vue
  src/js/components/SideBar/SideBar.vue
  src/js/components/SideBar/SideBarTabOptionsDate.vue
  src/js/components/SideBar/SideBarTabOptionsText.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/VoteTable/VoteList.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/components/VoteTable/VoteTableHeader.vue
  src/js/components/VoteTable/VoteTableItem.vue
  src/js/views/Vote.vue
Labels: 3. to review, design

#889 [1.4.0 beta1] Fix datetimepicker
  package.json
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/SideBar/SideBarTabOptionsDate.vue
Labels: 3. to review, bug, dependencies, enhancement

#890 set window title
  src/js/views/PollList.vue
  src/js/views/Vote.vue
Labels: 3. to review, design

#893 hide results
  lib/Controller/VoteController.php
  lib/Db/VoteMapper.php
  lib/Model/Acl.php
  src/js/components/Base/PollInformation.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
Labels: 4. to release, enhancement

#897 Add poll description to invitation mail
  lib/Service/MailService.php
Labels: 3. to review, enhancement

#898 Css fixes and tidy
  src/js/App.vue
  src/js/components/SideBar/SideBar.vue
  src/js/components/SideBar/SideBarTabOptions.vue
  src/js/components/SideBar/SideBarTabOptionsDate.vue
  src/js/components/SideBar/SideBarTabOptionsText.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
  src/js/components/VoteTable/VoteList.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/components/VoteTable/VoteTableHeader.vue
  src/js/components/VoteTable/VoteTableItem.vue
  src/js/store/modules/polls.js
  src/js/store/modules/votes.js
  src/js/views/PollList.vue
Labels: bug, design

#901 Adding a space character
  src/js/components/Base/PollInformation.vue
Labels: design

#911 Fix public user
  CHANGELOG.md
  lib/Controller/ShareController.php
  lib/Controller/SystemController.php
  lib/Controller/VoteController.php
  src/js/components/Base/ButtonDiv.vue
  src/js/components/VoteTable/VoteHeaderPublic.vue
Labels: 4. to release, bug
