Repository nextcloud/polls, pull requests merged in 2021-05, with the labels that each got.

#1516 Add polls:share:* CLI commands
  .gitignore
  appinfo/info.xml
  lib/Command/Share/Add.php
  lib/Command/Share/Remove.php
  lib/Command/Share/TShareCommand.php
  lib/Controller/ShareController.php
  lib/Model/Acl.php
  lib/Service/ShareService.php
  tests/Integration/App/AppTest.php
  tests/Integration/Command/Share/AddTest.php
  tests/Integration/Command/Share/RemoveTest.php
  tests/Integration/Command/Share/TShareCommandTest.php
  tests/phpunit.integration.xml
  tests/phpunit.xml
Labels: 3. to review, enhancement, php

#1604 tidy and maintenance
  .gitignore
  appinfo/routes.php
  composer.json
  lib/AppInfo/Application.php
  lib/Controller/PollController.php
  lib/Controller/PublicController.php
  lib/Controller/ShareController.php
  lib/Cron/JanitorCron.php
  lib/Cron/NotificationCron.php
  lib/Cron/UserDeletedJob.php
  lib/Db/CommentMapper.php
  lib/Db/LogMapper.php
  lib/Db/Model.php
  lib/Db/OptionMapper.php
  lib/Db/PollMapper.php
  lib/Db/PreferencesMapper.php
  lib/Db/ShareMapper.php
  lib/Db/SubscriptionMapper.php
  lib/Db/VoteMapper.php
  lib/Db/WatchMapper.php
  lib/Migration/Version0010Date20191227063812.php
  lib/Model/Acl.php
  lib/Service/CommentService.php
  lib/Service/MailService.php
  lib/Service/NotificationService.php
  lib/Service/OptionService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  lib/Service/SubscriptionService.php
  lib/Service/VoteService.php
  psalm-baseline.xml
  psalm.xml
  src/js/store/modules/share.js
  tests/Unit/Db/VoteMapperTest.php
Labels: refactor

#1620 Add delete action component with undelete
  src/js/components/Actions/ActionDelete.vue
  src/js/components/Comments/CommentItem.vue
  src/js/components/Options/OptionItemOwner.vue
  src/js/components/Options/OptionsDate.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Shares/SharesEffective.vue
  src/js/components/Shares/SharesPublic.vue
  src/js/components/Shares/SharesUnsent.vue
  src/js/components/VoteTable/VoteTable.vue
Labels: enhancement

#1627 Option to handle no as unvoted
  lib/Db/Poll.php
  lib/Db/VoteMapper.php
  lib/Migration/Version0200Date20210323120002.php
  lib/Service/VoteService.php
  src/js/components/Configuration/ConfigUseNo.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/store/modules/poll.js
Labels: enhancement

#1650 tidy icons and complete poll information
  .stylelintrc.js
  src/js/assets/scss/icons.scss
  src/js/components/Poll/PollInformation.vue
  src/js/store/modules/poll.js
Labels: enhancement

#1652 Catch email send errors on registration to public poll
  lib/Service/ShareService.php
  src/js/components/Poll/PublicRegisterModal.vue
Labels: bug

#1659 option owner "disallow"
  lib/Db/Option.php
  lib/Migration/Version0109Date20210323120002.php
Labels: bug

#1657 Add displayname to Invitation notice
  lib/Service/MailService.php
  src/js/components/Shares/SharesEffective.vue
  src/js/components/Shares/SharesUnsent.vue
Labels: enhancement

#1661 Disallow proposals on closed polls
  src/js/components/Configuration/ConfigClosing.vue
  src/js/components/Navigation/PollNavigationItems.vue
  src/js/components/Options/Confirmation.vue
  src/js/components/Options/OptionsDate.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Options/OptionsTextAdd.vue
  src/js/components/Poll/PollInformation.vue
  src/js/components/Poll/PollTitle.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/PollList/PollItemAdmin.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/SideBar/SideBarTabOptions.vue
  src/js/components/VoteTable/VoteItem.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/components/VoteTable/VoteTableHeaderItem.vue
  src/js/store/modules/poll.js
  src/js/views/Vote.vue
Labels: bug

#1662 simplify DOM and tidy CSS
  src/js/App.vue
  src/js/assets/scss/experimental.scss
  src/js/components/Base/Badge.vue
  src/js/components/Base/LoadingOverlay.vue
  src/js/components/Calendar/CalendarInfo.vue
  src/js/components/Calendar/CalendarPeek.vue
  src/js/components/Comments/CommentItem.vue
  src/js/components/Options/OptionItem.vue
  src/js/components/Options/OptionItemOwner.vue
  src/js/components/Poll/PollTitle.vue
  src/js/components/Shares/SharesEffective.vue
  src/js/components/Shares/SharesPublic.vue
  src/js/components/Shares/SharesUnsent.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/User/UserItem.vue
  src/js/components/VoteTable/VoteItem.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/components/VoteTable/VoteTableHeaderItem.vue
  src/js/views/Administration.vue
  src/js/views/PollList.vue
  src/js/views/Vote.vue
Labels: refactor

#1673 Allow URL-Parameters for username and email address in public share
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/Shares/SharesPublic.vue
Labels: enhancement

#1674 fix firstDayOfWeek #1560
  src/js/components/Configuration/ConfigProposals.vue
  src/js/components/Options/OptionsDateAdd.vue
Labels: bug

#1675 closing date
  src/js/components/Configuration/ConfigClosing.vue
  src/js/components/Configuration/ConfigProposals.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/PollList/PollItemAdmin.vue
  src/js/components/VoteTable/VoteTable.vue
Labels: bug

#1676 Add count of votes and options to poll information
  src/js/components/Poll/PollInformation.vue
  src/js/store/modules/votes.js
Labels: enhancement

#1663 add unique parameter to axios.get
  appinfo/routes.php
  src/js/store/modules/comments.js
  src/js/store/modules/options.js
  src/js/store/modules/poll.js
  src/js/store/modules/polls.js
  src/js/store/modules/pollsAdmin.js
  src/js/store/modules/settings.js
  src/js/store/modules/share.js
  src/js/store/modules/shares.js
  src/js/store/modules/subscription.js
  src/js/store/modules/votes.js
Labels: bug
