Repository nextcloud/polls, pull requests merged in 2021-01, with the labels that each got.

#1302 timed poll updates
  src/js/views/Vote.vue
Labels: 3. to review

#1335 fix #1326
  lib/Service/MailService.php
Labels: bug

#1327 Improve plural handling
  src/js/components/Base/PollInformation.vue
Labels: 3. to review, bug

#1334 fix #1325
  src/js/components/PollList/PollItem.vue
Labels: design

#1339 Refactor store
  appinfo/routes.php
  lib/Controller/CommentController.php
  lib/Controller/PollController.php
  lib/Controller/PreferencesController.php
  lib/Controller/PublicController.php
  lib/Controller/ShareController.php
  lib/Controller/VoteController.php
  lib/Model/Acl.php
  lib/Model/ContactGroup.php
  lib/Service/CommentService.php
  lib/Service/OptionService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  lib/Service/SubscriptionService.php
  lib/Service/VoteService.php
  package-lock.json
  package.json
  src/js/App.vue
  src/js/components/Base/Badge.vue
  src/js/components/Base/PersonalLink.vue
  src/js/components/Base/PublicRegisterModal.vue
  src/js/components/Calendar/CalendarPeek.vue
  src/js/components/Navigation/Navigation.vue
  src/js/components/Options/OptionCloneDate.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/Settings/FeatureSettings.vue
  src/js/components/Shares/SharesEffective.vue
  src/js/components/Shares/SharesPublic.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/Subscription/Subscription.vue
  src/js/main.js
  src/js/store/modules/poll.js
  src/js/store/modules/share.js
  src/js/store/modules/subModules/comments.js
  src/js/store/modules/subModules/options.js
  src/js/store/modules/subModules/shares.js
  src/js/store/modules/subModules/votes.js
  src/js/store/modules/subscription.js
  src/js/views/PollList.vue
  src/js/views/Vote.vue
Labels: 2. developing

#1340 Make sure only valid votes are counted
  lib/Db/VoteMapper.php
  lib/Model/Acl.php
  lib/Service/VoteService.php
  src/js/components/VoteTable/VoteTableVoteItem.vue
  src/js/store/modules/subModules/votes.js
Labels: bug

#1344 disallow commenting with public shares
  lib/Model/Acl.php
Labels: bug

#1347 Fix usersearch
  CHANGELOG.md
  lib/Model/UserGroupClass.php
Labels: bug

#1356 fix migration
  lib/Db/Log.php
  lib/Db/LogMapper.php
  lib/Migration/Version0107Date20201210204702.php
  lib/Migration/Version0107Date20201210213303.php
  lib/Migration/Version0107Date20201217071304.php
  lib/Migration/Version0107Date20210101161105.php
  lib/Migration/Version0107Date20210121220707.php
  lib/Service/LogService.php
  lib/Service/MailService.php
  tests/Unit/Factories/LogFactory.php
Labels: bug

#1374 fix uniqueConstraint error
  src/js/components/Options/OptionsDateShift.vue
Labels: backport stable-1.7, bug
