Repository nextcloud/polls, pull requests merged in 2021-11, with the labels that each got.

#2060 Feature/disable long poll
  CHANGELOG.md
  appinfo/info.xml
  lib/Controller/SettingsController.php
  lib/Controller/WatchController.php
  lib/Model/Settings/AppSettings.php
  lib/Service/SettingsService.php
  package-lock.json
  package.json
  src/js/App.vue
  src/js/components/Settings/AdminMisc.vue
  src/js/mixins/watchPolls.js
  src/js/store/modules/appSettings.js
  webpack.config.js
Labels: enhancement

#2078 l10n: Change name to a capital letter
  appinfo/info.xml
Labels: translation

#2088 Update npm and node engines versions
  package.json
Labels: dependencies

#2100 update php-cs-fixer and nextcloud/coding-standard
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  composer.lock
  lib/Service/OptionService.php
Labels: dependencies

#2096 fix sort by rank
  lib/Service/OptionService.php
Labels: bug

#2080 Duplicate check status message
  lib/Service/ShareService.php
  src/js/components/Poll/PublicRegisterModal.vue
Labels: UX

#2077 Redesign share tab
  appinfo/routes.php
  lib/Controller/ShareController.php
  lib/Db/Poll.php
  lib/Db/Share.php
  lib/Migration/TableSchema.php
  lib/Migration/Version030400Date20211125120000.php
  lib/Service/ShareService.php
  src/js/assets/scss/hacks.scss
  src/js/components/Base/ButtonDiv.vue
  src/js/components/Base/ConfigBox.vue
  src/js/components/Options/Confirmation.vue
  src/js/components/Poll/PollTitle.vue
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/Shares/ShareItemAllUsers.vue
  src/js/components/Shares/SharePublicAdd.vue
  src/js/components/Shares/SharesList.vue
  src/js/components/Shares/SharesListUnsent.vue
  src/js/components/Shares/SharesPublic.vue
  src/js/components/Shares/SharesUnsent.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/User/UserItem.vue
  src/js/components/User/UserSearch.vue
  src/js/store/modules/poll.js
  src/js/store/modules/share.js
  src/js/store/modules/shares.js
  src/js/store/modules/votes.js
  src/js/views/SideBar.vue
Labels: design, UX

#2114 Fix wording in autoreminder explanation
  src/js/components/Configuration/AutoReminderInformation.vue
Labels: bug
