Repository nextcloud/polls, pull requests merged in 2022-02, with the labels that each got.

#2220 store refactoring
  lib/Db/Comment.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/Vote.php
  lib/Model/UserGroup/IUserBase.php
  src/js/App.vue
  src/js/components/Combo/VoteItem.vue
  src/js/components/Comments/CommentItem.vue
  src/js/components/Export/ExportPoll.vue
  src/js/components/Options/Counter.vue
  src/js/components/Options/OptionItem.vue
  src/js/components/Options/OptionItemOwner.vue
  src/js/components/Options/OptionsTextAdd.vue
  src/js/components/Poll/PollInformation.vue
  src/js/components/Poll/PollTitle.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/PollList/PollItemAdmin.vue
  src/js/components/SideBar/SideBarTabDatePolls.vue
  src/js/components/User/UserItem.vue
  src/js/components/VoteTable/VoteItem.vue
  src/js/components/VoteTable/VoteTableHeaderItem.vue
  src/js/helpers/arrayHelper.js
  src/js/store/modules/activity.js
  src/js/store/modules/combo.js
  src/js/store/modules/options.js
  src/js/store/modules/poll.js
  src/js/store/modules/polls.js
  src/js/store/modules/votes.js
  src/js/views/Administration.vue
  src/js/views/PollList.vue
  src/js/views/PollSelector.vue
Labels: refactor

#2222 migration fixes
  lib/Migration/TableSchema.php
Labels: bug

#2223 remove obsolete eslint dependencies
  .github/workflows/app-code-check.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  package-lock.json
  package.json
Labels: dependencies

#2227 Use @nextcloud/stylelint-config
  .stylelintrc.js
  package-lock.json
  package.json
  src/js/assets/scss/dashboard.scss
  src/js/assets/scss/print.scss
  src/js/components/Base/Badge.vue
  src/js/components/Base/InputDiv.vue
  src/js/components/Calendar/CalendarInfo.vue
  src/js/components/Combo/ComboTable.vue
  src/js/components/Combo/VoteItem.vue
  src/js/components/Options/OptionItem.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/VoteTable/VoteItem.vue
  src/js/components/VoteTable/VoteTable.vue
  stylelint.config.js
Labels: dependencies

#2233 remove devDependencies from package.json
  package-lock.json
  package.json
Labels: dependencies

#2234 use @nextcloud/babel-config
  babel.config.js
  babel.config.json
  package-lock.json
  package.json
Labels: dependencies

#2239 exclude selected events from email notificaton
  lib/Event/CommentDeleteEvent.php
  lib/Event/PollOptionReorderedEvent.php
  lib/Event/ShareChangedRegistrationConstraintEvent.php
  lib/Event/ShareEvent.php
  lib/Listener/BaseListener.php
Labels: enhancement

#2251 add missing CommentEvent::Add in notification mail
  lib/Model/Mail/NotificationMail.php
Labels: bug

#2267 changed class loading and change error level to warning
  lib/Model/UserGroup/Circle.php
  lib/Model/UserGroup/Contact.php
  lib/Model/UserGroup/ContactGroup.php
  lib/Model/UserGroup/Email.php
  lib/Model/UserGroup/GenericUser.php
  lib/Model/UserGroup/Group.php
  lib/Model/UserGroup/User.php
  lib/Model/UserGroup/UserBase.php
Labels: bug

#2268 return email address in user search for users and contacts resolve #2264
  lib/Model/UserGroup/Contact.php
  lib/Model/UserGroup/User.php
Labels: enhancement

#2272 fix export
  CHANGELOG.md
  src/js/components/Export/ExportPoll.vue
Labels: bug

#2279 invalid function call in listener when deleting users from nextcloud
  lib/Exceptions/OCPEventException.php
  lib/Listener/BaseListener.php
  lib/Listener/GroupDeletedListener.php
  lib/Listener/UserDeletedListener.php
Labels: bug

#2283 add type and inputmode and few optimizations
  src/js/components/Base/InputDiv.vue
  src/js/components/Configuration/ConfigOptionLimit.vue
  src/js/components/Configuration/ConfigVoteLimit.vue
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/Settings/AdminMisc.vue
Labels: enhancement

#2288 l10n: Correct spelling
  CHANGELOG.md
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/Settings/AdminSettings/AdminLegal.vue
  src/js/components/Settings/UserSettings/PerformanceSettings.vue
  src/js/views/AdminSettingsPage.vue
Labels: translation

#2289 rename public and hidden polls to open and private
  src/js/assets/scss/icons-dark.scss
  src/js/assets/scss/icons.scss
  src/js/components/Poll/PollInformation.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/PollList/PollItemAdmin.vue
  src/js/components/Settings/AdminSettings/AdminShareSettings.vue
  src/js/components/Shares/ShareItemAllUsers.vue
  src/js/components/User/UserItem.vue
  src/js/store/modules/polls.js
Labels: translation
