Repository nextcloud/polls, pull requests merged in 2022-07, with the labels that each got.

#2489 modularize workflows and add caching
  .github/actions/get-polls-version/action.yml
  .github/actions/setup-composer/action.yml
  .github/actions/setup-node/action.yml
  .github/actions/setup-server/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/phpunit.yml
  .github/workflows/publish_beta.yml
  .github/workflows/static-analysis.yml
  appinfo/info.xml
Labels: dependencies, actions

#2493 fix avatar of public users
  src/js/components/User/UserItem.vue
Labels: bug

#2495 fix unsubscribe from public poll
  lib/Controller/PublicController.php
Labels: bug

#2499 l10n: Correct spelling
  lib/Service/ActivityService.php
  src/js/components/User/UserMenu.vue
Labels: translation

#2511 experimental comment styling
  src/js/components/Comments/CommentItem.vue
  src/js/components/Comments/Comments.vue
  src/js/components/Settings/UserSettings/StyleSettings.vue
  src/js/store/modules/settings.js
Labels: enhancement, design
