Repository nextcloud/polls, pull requests merged in 2022-12, with the labels that each got.

#2678 Handle userid being null in NotificationService
  lib/Service/NotificationService.php
Labels: bug, 4. to release, php

#2696 scoped and optimized dashboard css
  src/js/views/Dashboard.vue
Labels: bug

#2695 Change registration dialog
  src/js/App.vue
  src/js/components/Base/InputDiv.vue
  src/js/components/Poll/PublicRegisterModal.vue
Labels: enhancement, 3. text review

#2704 Update vote page design according to NC design refresh
  src/js/assets/scss/print.scss
  src/js/components/Options/Counter.vue
  src/js/components/VoteTable/VoteTable.vue
Labels: enhancement, design

#2699 l10n: Correct typo
  src/js/components/Poll/PublicRegisterModal.vue
Labels: translation

#2711 Avoid timestamp overflow
  CHANGELOG.md
  lib/Migration/TableSchema.php
Labels: bug
