Repository nextcloud/polls, pull requests merged in 2022-09, with the labels that each got.

#2571 implement @nextcloud/vue-richtext
  package-lock.json
  package.json
  src/js/components/Activity/ActivityItem.vue
  src/js/components/Poll/PublicRegisterModal.vue
Labels: dependencies

#2573 use @nextcloud/initial-state
  package-lock.json
  package.json
Labels: dependencies

#2585 Hide deprecated projects in sidebar by default
  src/js/views/SideBar.vue
Labels: enhancement, 4. to release

#2590 Revert "Merge pull request #2585 from nextcloud/enh/hide-projects-2"
  src/js/views/SideBar.vue
Labels: 3. to review

#2591 change watchPolls
  src/js/Exceptions/Exceptions.js
  src/js/mixins/watchPolls.js
Labels: refactor

#2592 Hide deprecated projects in sidebar by default
  src/js/views/SideBar.vue
Labels: enhancement

#2587 move some dev-deps to global
  .github/workflows/phpunit.yml
  Makefile
  composer.json
  composer.lock
  lib/Command/Db/Rebuild.php
  lib/Db/LogMapper.php
  lib/Db/OptionMapper.php
  lib/Db/PreferencesMapper.php
  lib/Db/ShareMapper.php
  lib/Db/SubscriptionMapper.php
  lib/Db/VoteMapper.php
  lib/Listener/BaseListener.php
  lib/Migration/TableSchema.php
  lib/Migration/Version030400Date20211125120000.php
  lib/Service/OptionService.php
  lib/Service/SubscriptionService.php
Labels: dependencies, php

#2598 Collection of small fixes before release 4.0
  lib/AppInfo/Application.php
  lib/Provider/ResourceProvider.php
  package-lock.json
  package.json
  src/js/assets/scss/hacks.scss
  src/js/collections.js
  src/js/components/Configuration/ConfigAutoReminder.vue
  src/js/components/Create/CreateDlg.vue
  src/js/components/Options/OptionsDate.vue
  src/js/components/Options/OptionsDateAdd.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Poll/PollInfoLine.vue
  src/js/components/Shares/SharePublicAdd.vue
  src/js/components/Shares/SharesList.vue
  src/js/components/Shares/SharesListUnsent.vue
  src/js/components/SideBar/SideBarTabActivity.vue
  src/js/components/SideBar/SideBarTabCollaboration.vue
  src/js/components/SideBar/SideBarTabComments.vue
  src/js/components/User/UserItem.vue
  src/js/components/User/UserMenu.vue
  src/js/main.js
  src/js/mixins/watchPolls.js
  src/js/views/Administration.vue
  src/js/views/Combo.vue
  src/js/views/NotFound.vue
  src/js/views/PollList.vue
  src/js/views/PollSelector.vue
  src/js/views/SideBar.vue
  src/js/views/Vote.vue
  webpack.config.js
Labels: bug, refactor

#2605 Fixes for Version 3.8.1
  lib/Controller/PublicController.php
  lib/Db/Comment.php
  lib/Db/Log.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/Preferences.php
  lib/Db/Share.php
  lib/Db/Subscription.php
  lib/Db/Vote.php
  lib/Db/Watch.php
  lib/Model/Settings/AppSettings.php
Labels: bug

#2603 Code maintenance
  lib/Controller/PublicController.php
  lib/Db/Comment.php
  lib/Db/Log.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/Preferences.php
  lib/Db/Share.php
  lib/Db/Subscription.php
  lib/Db/Vote.php
  lib/Db/Watch.php
  lib/Exceptions/InvalidPollIdException.php
  lib/Model/Acl.php
  lib/Model/Mail/NotificationMail.php
  lib/Model/Settings/AppSettings.php
  lib/Service/MailService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  lib/Service/UserService.php
  lib/Service/VoteService.php
  src/js/components/Options/OptionsDate.vue
Labels: bug, enhancement, refactor

#2609 update christophwurst/nextcloud to nextcloud/ocp
  .github/workflows/static-analysis.yml
  composer.json
  composer.lock
Labels: dependencies
