Repository nextcloud/polls, pull requests merged in 2022-08, with the labels that each got.

#2527 skip participant on error
  CHANGELOG.md
  src/js/components/Export/ExportPoll.vue
Labels: bug

#2531 Update npm and node engines versions
  package.json
Labels: dependencies

#2548 manually update @nextcloud/eslint-config@8.1.2
  package-lock.json
  package.json
  src/js/App.vue
  src/js/components/Base/FlexSpacer.vue
  src/js/components/Calendar/CalendarPeek.vue
  src/js/components/Combo/ComboTable.vue
  src/js/components/Comments/Comments.vue
  src/js/components/Export/ExportPoll.vue
  src/js/components/Options/OptionsDateAdd.vue
  src/js/components/Poll/MarkUpDescription.vue
  src/js/components/Poll/PublicEmail.vue
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/User/UserMenu.vue
  src/js/components/User/UserSearch.vue
  src/js/components/VoteTable/VoteColumn.vue
  src/js/mixins/adminSettingsMixin.js
  src/js/mixins/writePoll.js
  src/js/store/modules/combo.js
  src/js/store/modules/index.js
  src/js/store/modules/options.js
  src/js/store/modules/polls.js
  src/js/views/Administration.vue
Labels: dependencies

#2550 l10n: Change "mail" to "email"
  src/js/components/Actions/ActionSendConfirmedOptions.vue
Labels: translation

#2563 Fix: addBlulk endpoint no longer requires admin
  lib/Controller/OptionController.php
Labels: bug

#2559 Fix darkmode in NC25+
  appinfo/info.xml
  src/js/assets/scss/colors-dark.scss
  src/js/assets/scss/colors.scss
  src/js/assets/scss/hacks.scss
  src/js/assets/scss/theming.scss
  src/js/views/Combo.vue
  src/js/views/Vote.vue
Labels: design

#2568 add types for internal PHP classes
  .github/workflows/static-analysis.yml
  lib/Db/Comment.php
  lib/Db/Log.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/Preferences.php
  lib/Db/Share.php
  lib/Db/Subscription.php
  lib/Db/Vote.php
  lib/Db/Watch.php
  lib/Model/Settings/AppSettings.php
Labels: bug
