Repository nextcloud/polls, pull requests merged in 2022-05, with the labels that each got.

#2408 Fix poll export, if downloader did not vote
  src/js/components/Export/ExportPoll.vue
  src/js/store/modules/poll.js
Labels: bug

#2413 l10n: Reconstruction of sentences and change l10n
  src/js/components/Settings/UserSettings/CalendarSettings.vue
  src/js/views/Navigation.vue
Labels: translation

#2424 Fix click button on adding date option
  src/js/components/SideBar/SideBarTabOptions.vue
Labels: bug

#2425 Separate public userId from displayName
  lib/Controller/AdminController.php
  lib/Controller/CommentApiController.php
  lib/Controller/CommentController.php
  lib/Controller/OptionApiController.php
  lib/Controller/OptionController.php
  lib/Controller/PageController.php
  lib/Controller/PollController.php
  lib/Controller/PreferencesController.php
  lib/Controller/PublicController.php
  lib/Controller/SettingsController.php
  lib/Controller/ShareApiController.php
  lib/Controller/ShareController.php
  lib/Controller/SubscriptionController.php
  lib/Controller/VoteController.php
  lib/Controller/WatchController.php
  lib/Db/Comment.php
  lib/Db/Option.php
  lib/Db/Vote.php
  lib/Model/Acl.php
  lib/Model/UserGroup/UserBase.php
  lib/Service/AnonymizeService.php
  lib/Service/CommentService.php
  lib/Service/OptionService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  lib/Service/SubscriptionService.php
  lib/Service/VoteService.php
  lib/Service/WatchService.php
  src/js/store/modules/subModules/acl.js
Labels: enhancement, refactor

#2441 strip illegal characters from sheet name
  lib/Db/VoteMapper.php
  src/js/components/Export/ExportPoll.vue
Labels: bug

#2442 fix empty array result on user search
  lib/Service/SystemService.php
Labels: bug

#2444 fix legal links in register dialog
  lib/Model/Settings/AppSettings.php
Labels: bug

#2443 l10n: Add word "Name"
  src/js/components/Poll/PublicRegisterModal.vue
Labels: translation
