Repository nextcloud/polls, pull requests merged in 2022-03, with the labels that each got.

#2310 use @nextcloud/webpack-vue-config
  package-lock.json
  package.json
  templates/admin.php
  templates/polls.tmpl.php
  templates/settings.php
  webpack.config.js
Labels: dependencies, refactor

#2311 Support material design icons with configbox
  src/js/components/Base/ConfigBox.vue
Labels: enhancement, design

#2312 fix modal heights
  src/js/components/Options/OptionsDate.vue
  src/js/views/Administration.vue
Labels: bug, design, translation

#2323 Add ISearch::TYPE_EMAIL to user search
  lib/Model/UserGroup/UserBase.php
Labels: bug

#2324 Fix Exception upon validation of usernames and email addresses
  lib/Controller/PublicController.php
  lib/Service/SystemService.php
Labels: bug

#2326 remove poll route on admin page
  src/js/components/PollList/PollItem.vue
  src/js/views/Administration.vue
Labels: bug

#2325 l10n: Correct typo
  src/js/views/Administration.vue
Labels: translation

#2327 add email addresses to poll export for owner
  lib/Model/Mail/MailBase.php
  lib/Service/MailService.php
  lib/Service/PollService.php
  src/js/components/Export/ExportPoll.vue
  src/js/components/User/UserMenu.vue
Labels: enhancement

#2328 migrate access type hidden, public to private, open
  lib/Db/Poll.php
  lib/Migration/TableSchema.php
  lib/Model/Acl.php
  lib/Service/PollService.php
  src/js/components/Configuration/ConfigAccess.vue
  src/js/components/Poll/PollInfoLine.vue
  src/js/components/Poll/PollInformation.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/PollList/PollItemAdmin.vue
  src/js/components/Shares/ShareItemAllUsers.vue
  src/js/components/User/UserItem.vue
  src/js/store/modules/poll.js
  src/js/store/modules/polls.js
Labels: enhancement

#2339 Add bulk import for text polls
  appinfo/routes.php
  lib/Controller/OptionController.php
  lib/Service/OptionService.php
  src/js/App.vue
  src/js/components/Base/ConfigBox.vue
  src/js/components/Options/OptionCloneDate.vue
  src/js/components/Options/OptionsTextAddBulk.vue
  src/js/components/SideBar/SideBarTabOptions.vue
  src/js/store/modules/options.js
Labels: enhancement

#2341 Fix/design 3.6
  src/js/assets/scss/icons.scss
  src/js/components/Options/OptionsText.vue
  src/js/components/SideBar/SideBarTabUserOptions.vue
  src/js/views/SideBar.vue
Labels: bug, design, refactor
