Repository nextcloud/polls, pull requests merged in 2022-01, with the labels that each got.

#2163 Don't allow adding proposal with public share
  lib/Model/Acl.php
Labels: bug

#2155 l10n: Correct spelling
  lib/Service/ActivityService.php
  lib/Settings/ActivityVote.php
Labels: translation

#2164 fix store
  src/js/App.vue
  src/js/components/Settings/AdminMisc.vue
  src/js/components/Settings/AdminPollCreation.vue
  src/js/components/Settings/AdminShareSettings.vue
  src/js/mixins/watchPolls.js
  src/js/store/modules/appSettings.js
Labels: bug

#2165 Tense and corrections in activities
  lib/Service/ActivityService.php
Labels: translation

#2169 add excel and csv download
  lib/Controller/PollController.php
  lib/Model/Acl.php
  lib/Model/Settings/AppSettings.php
  lib/Service/PollService.php
  lib/Service/SettingsService.php
  package-lock.json
  package.json
  src/js/components/Export/ExportPoll.vue
  src/js/components/Poll/PollHeaderButtons.vue
  src/js/components/Settings/AdminPollDownload.vue
  src/js/store/modules/appSettings.js
  src/js/store/modules/options.js
  src/js/store/modules/subModules/acl.js
  src/js/store/modules/votes.js
  src/js/views/AdminSettingsPage.vue
Labels: enhancement, 3. text review

#2176 l10n: Change to uppercase
  src/js/components/Export/ExportPoll.vue
  src/js/store/modules/votes.js
Labels: translation

#2178 skip and remove notification on exception
  lib/Notification/Notifier.php
Labels: bug

#2190 linkify options
  CHANGELOG.md
  package-lock.json
  package.json
  src/js/components/Options/OptionItem.vue
Labels: enhancement

#2204 Add occ command to validate and recreate database structure
  appinfo/info.xml
  lib/Command/Db/Rebuild.php
  lib/Migration/TableSchema.php
  lib/Service/ActivityService.php
  psalm-baseline.xml
  src/js/components/Options/OptionItem.vue
Labels: enhancement

#2205 Deprecations
  lib/Controller/PreferencesController.php
  lib/Controller/PublicController.php
  lib/Cron/GroupDeletedJob.php
  lib/Cron/UserDeletedJob.php
  lib/Db/Comment.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/Preferences.php
  lib/Db/Share.php
  lib/Db/Vote.php
  lib/Event/BaseEvent.php
  lib/Helper/Container.php
  lib/Model/Acl.php
  lib/Model/Mail/MailBase.php
  lib/Model/UserGroup/Circle.php
  lib/Model/UserGroup/Contact.php
  lib/Model/UserGroup/ContactGroup.php
  lib/Model/UserGroup/Email.php
  lib/Model/UserGroup/GenericUser.php
  lib/Model/UserGroup/Group.php
  lib/Model/UserGroup/IUserBase.php
  lib/Model/UserGroup/User.php
  lib/Model/UserGroup/UserBase.php
  lib/Provider/ResourceProvider.php
  lib/Service/ActivityService.php
  lib/Service/LogService.php
  lib/Service/MailService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  lib/Service/SystemService.php
  psalm-baseline.xml
Labels: refactor

#2215 Fix/translation
  lib/Activity/PollChanges.php
  lib/Model/Mail/InvitationMail.php
  lib/Model/Mail/MailBase.php
  lib/Model/Mail/NotificationMail.php
  lib/Model/Mail/ReminderMail.php
  lib/Provider/ActivityProvider.php
  lib/Provider/SearchProvider.php
  lib/Service/ActivityService.php
  lib/Settings/ActivitySettings.php
  lib/Settings/ActivityVote.php
  lib/Settings/AdminSection.php
  lib/Settings/PersonalSection.php
Labels: translation

#2212 Refactoring mail classes
  lib/Model/Mail/InvitationMail.php
  lib/Model/Mail/MailBase.php
  lib/Model/Mail/NotificationMail.php
  lib/Model/Mail/ReminderMail.php
  lib/Service/MailService.php
Labels: refactor
