Repository nextcloud/polls, pull requests merged in 2022-06, with the labels that each got.

#2449 Standardize InputDiv
  src/js/App.vue
  src/js/components/Base/InputDiv.vue
  src/js/components/Comments/CommentAdd.vue
  src/js/components/Configuration/ConfigOptionLimit.vue
  src/js/components/Configuration/ConfigTitle.vue
  src/js/components/Configuration/ConfigVoteLimit.vue
  src/js/components/Create/CreateDlg.vue
  src/js/components/Options/OptionCloneDate.vue
  src/js/components/Options/OptionsDateShift.vue
  src/js/components/Options/OptionsTextAdd.vue
  src/js/components/Poll/PublicEmail.vue
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/Settings/AdminSettings/AdminCombo.vue
  src/js/components/Settings/AdminSettings/AdminEmail.vue
  src/js/components/Settings/AdminSettings/AdminHideMailAddresses.vue
  src/js/components/Settings/AdminSettings/AdminLegal.vue
  src/js/components/Settings/AdminSettings/AdminMisc.vue
  src/js/components/Settings/AdminSettings/AdminPerformance.vue
  src/js/components/Settings/AdminSettings/AdminPollCreation.vue
  src/js/components/Settings/AdminSettings/AdminPollDownload.vue
  src/js/components/Settings/AdminSettings/AdminShareSettings.vue
  src/js/components/Settings/UserSettings/CalendarSettings.vue
  src/js/components/Settings/UserSettings/FeatureSettings.vue
  src/js/components/Settings/UserSettings/PerformanceSettings.vue
  src/js/components/Settings/UserSettings/StyleSettings.vue
  src/js/views/AdminSettingsPage.vue
  src/js/views/UserSettingsPage.vue
Labels: enhancement, refactor

#2451 l10n: Add a dot
  src/js/components/Poll/PublicRegisterModal.vue
Labels: translation

#2464 [3.7.0-beta5] fix description width bug
  src/js/components/Base/InputDiv.vue
Labels: bug, design

#2465 remove term username
  src/js/components/Poll/PublicRegisterModal.vue
Labels: translation

#2467 Refactoring of the client Server communication
  lib/Controller/AdminController.php
  lib/Controller/CommentApiController.php
  lib/Controller/CommentController.php
  lib/Controller/OptionApiController.php
  lib/Controller/OptionController.php
  lib/Controller/PollApiController.php
  lib/Controller/PollController.php
  lib/Controller/PreferencesController.php
  lib/Controller/PublicController.php
  lib/Controller/ResponseHandle.php
  lib/Controller/SettingsController.php
  lib/Controller/ShareApiController.php
  lib/Controller/ShareController.php
  lib/Controller/SubscriptionApiController.php
  lib/Controller/SubscriptionController.php
  lib/Controller/SystemController.php
  lib/Controller/VoteApiController.php
  lib/Controller/VoteController.php
  lib/Controller/WatchController.php
  src/js/components/Poll/PublicEmail.vue
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/Settings/AdminSettings/AdminCombo.vue
  src/js/components/Settings/AdminSettings/AdminHideMailAddresses.vue
  src/js/components/Settings/AdminSettings/AdminPollCreation.vue
  src/js/components/Settings/AdminSettings/AdminPollDownload.vue
  src/js/components/Settings/AdminSettings/AdminShareSettings.vue
  src/js/components/User/UserMenu.vue
  src/js/components/User/UserSearch.vue
  src/js/mixins/adminSettingsMixin.js
  src/js/mixins/watchPolls.js
  src/js/router.js
  src/js/store/modules/appSettings.js
  src/js/store/modules/combo.js
  src/js/store/modules/comments.js
  src/js/store/modules/options.js
  src/js/store/modules/poll.js
  src/js/store/modules/polls.js
  src/js/store/modules/pollsAdmin.js
  src/js/store/modules/settings.js
  src/js/store/modules/share.js
  src/js/store/modules/shares.js
  src/js/store/modules/subscription.js
  src/js/store/modules/votes.js
Labels: refactor

#2468 fix endless redirects
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/router.js
  src/js/store/modules/share.js
Labels: bug

#2473 Allow logging out from a public poll, when cookie is set
  src/js/components/User/UserMenu.vue
  src/js/helpers/cookieHelper.js
  src/js/router.js
Labels: enhancement

#2476 Linkify comments
  src/js/components/Comments/CommentItem.vue
Labels: enhancement
