Repository nextcloud/polls, pull requests merged in 2023-05, with the labels that each got.

#2885 use NcNoteCard
  CHANGELOG.md
  src/js/components/SideBar/SideBarTabConfiguration.vue
Labels: enhancement, design

#2893 Fix app update and duplicate removal
  README.md
  appinfo/info.xml
  lib/Command/Db/Purge.php
  lib/Command/Db/Rebuild.php
  lib/Db/LogMapper.php
  lib/Db/OptionMapper.php
  lib/Db/PreferencesMapper.php
  lib/Db/ShareMapper.php
  lib/Db/SubscriptionMapper.php
  lib/Db/TableManager.php
  lib/Db/VoteMapper.php
  lib/Migration/RepairSteps/DeleteInvalidRecords.php
  lib/Migration/RepairSteps/Install.php
  lib/Migration/TableSchema.php
  lib/Migration/Version050005Date20230506203301.php
Labels: bug, refactor

#2890 Add Nextcloud 27 support
  appinfo/info.xml
Labels: 4. to release

#2905 Use the color-primary-element* variables
  src/js/assets/scss/hacks.scss
  src/js/components/Base/BadgeDiv.vue
  src/js/components/Comments/CommentItem.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/PollList/PollItem.vue
  src/js/views/Dashboard.vue
Labels: bug, design, 4. to release

#2906 Replace deprecated NcMultiselect with NcSelect
  src/js/App.vue
  src/js/components/Base/ConfigBox.vue
  src/js/components/Base/InputDiv.vue
  src/js/components/Options/OptionCloneDate.vue
  src/js/components/Options/OptionsDateShift.vue
  src/js/components/Settings/AdminSettings/AdminCombo.vue
  src/js/components/Settings/AdminSettings/AdminHideMailAddresses.vue
  src/js/components/Settings/AdminSettings/AdminPollCreation.vue
  src/js/components/Settings/AdminSettings/AdminPollDownload.vue
  src/js/components/Settings/AdminSettings/AdminShareSettings.vue
  src/js/components/User/UserSearch.vue
Labels: enhancement, refactor

#2907 Replace vue-richtext with NcRichText
  package-lock.json
  package.json
  src/js/components/Activity/ActivityItem.vue
  src/js/components/Poll/PublicRegisterModal.vue
Labels: dependencies, refactor

#2912 Remove old polls from relevant list
  lib/Db/OptionMapper.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/Preferences.php
  lib/Db/TableManager.php
  lib/Listener/BaseListener.php
  lib/Migration/TableSchema.php
  lib/Migration/Version050100Date20230515083001.php
  lib/Service/PollService.php
  src/js/components/Settings/UserSettings/FeatureSettings.vue
  src/js/store/modules/polls.js
  src/js/store/modules/settings.js
Labels: enhancement, UX, 3. text review

#2916 Change vote page design (beta setting)
  lib/Db/Preferences.php
  src/js/components/Settings/UserSettings/StyleSettings.vue
  src/js/components/VoteTable/VoteColumn.vue
  src/js/components/VoteTable/VoteItem.vue
  src/js/store/modules/settings.js
  src/js/views/Vote.vue
Labels: enhancement, design, UX

#2921 don't use full store for dashboard widget
  src/js/dashboard.js
Labels: refactor

#2924 fix export with nullish email addresses
  lib/Model/User/Email.php
  lib/Model/User/GenericUser.php
  lib/Service/UserService.php
Labels: bug
