Repository nextcloud/polls, pull requests merged in 2023-08, with the labels that each got.

#3003 automate releases and notification
  .github/BETA_NOTIFICATION.md
  .github/RELEASE_NOTIFICATION.md
  .github/actions/get-polls-version/action.yml
  .github/workflows/publish_beta.yml
  .github/workflows/publish_release.yml
Labels: actions

#3009 Fixing API
  appinfo/routes.php
  lib/Controller/CommentApiController.php
  lib/Controller/PollApiController.php
  lib/Controller/ShareController.php
  lib/Controller/SubscriptionApiController.php
  lib/Controller/VoteApiController.php
  lib/Service/OptionService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  src/js/Api/polls.js
  src/js/store/modules/subscription.js
Labels: bug

#3022 Code maintenence
  lib/Cron/GroupDeletedJob.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/ShareMapper.php
  lib/Db/SubscriptionMapper.php
  lib/Db/VoteMapper.php
  lib/Event/BaseEvent.php
  lib/Event/CommentEvent.php
  lib/Event/OptionEvent.php
  lib/Event/ShareEvent.php
  lib/Event/VoteEvent.php
  lib/Exceptions/BadRequestException.php
  lib/Exceptions/ContactGroupNotFound.php
  lib/Exceptions/MultipleContactsFound.php
  lib/Helper/Trace.php
  lib/Listener/CommentListener.php
  lib/Model/Acl.php
  lib/Model/CalendarEvent.php
  lib/Model/Group/Circle.php
  lib/Service/PollService.php
  lib/Service/SystemService.php
  psalm-baseline.xml
  psalm.xml
  tests/Unit/Db/PollMapperTest.php
Labels: refactor

#3024 Refactor database operations for commands, repair steps and migrations
  lib/Command/Command.php
  lib/Command/Db/CleanMigrations.php
  lib/Command/Db/CreateIndices.php
  lib/Command/Db/Purge.php
  lib/Command/Db/Rebuild.php
  lib/Command/Db/RemoveIndices.php
  lib/Command/Db/ResetWatch.php
  lib/Db/IndexManager.php
  lib/Db/TableManager.php
  lib/Migration/FixVotes.php
  lib/Migration/RepairSteps/CreateIndices.php
  lib/Migration/RepairSteps/CreateTables.php
  lib/Migration/RepairSteps/DeleteInvalidRecords.php
  lib/Migration/RepairSteps/DropOrphanedColumns.php
  lib/Migration/RepairSteps/DropOrphanedTables.php
  lib/Migration/RepairSteps/Install.php
  lib/Migration/RepairSteps/RemoveIndices.php
  lib/Migration/RepairSteps/RemoveObsoleteMigrations.php
  lib/Migration/RepairSteps/UpdateHashes.php
  lib/Migration/RepairSteps/UpdateInteraction.php
  lib/Migration/Version050100Date20230515083001.php
Labels: refactor

#3034 Add label for public shares
  CHANGELOG.md
  appinfo/routes.php
  lib/Controller/ShareController.php
  lib/Service/ShareService.php
  src/js/Api/shares.js
  src/js/components/Shares/ShareItem.vue
  src/js/components/Shares/SharesList.vue
  src/js/components/User/UserItem.vue
  src/js/store/modules/shares.js
Labels: enhancement

#3037 fix activity
  lib/Provider/ActivityProvider.php
  lib/Service/ActivityService.php
Labels: bug

#3043 Fix deleteComment url
  src/js/Api/public.js
Labels: bug
