Repository nextcloud/polls, pull requests merged in 2023-09, with the labels that each got.

#3051 remove console error
  src/js/components/Options/OptionsDate.vue
Labels: bug

#3052 eliminate focus-trap console errors and fix styling of auto reminder information
  src/js/components/Calendar/CalendarPeek.vue
  src/js/components/Configuration/AutoReminderInformation.vue
  src/js/components/Configuration/ConfigAutoReminder.vue
  src/js/components/Poll/PollHeaderButtons.vue
Labels: bug, design

#3053 fix displayname in public registration
  lib/Controller/PublicController.php
  lib/Service/ShareService.php
Labels: bug

#3054 Release 5.3.0
  CHANGELOG.md
  appinfo/info.xml
Labels: Release

#3062 Fix creating public shares
  lib/Service/ShareService.php
Labels: bug

#3063 5.3.1
  CHANGELOG.md
  appinfo/info.xml
Labels: Release

#3069 Fix/migration-error
  CHANGELOG.md
  appinfo/info.xml
  lib/Migration/TableSchema.php
Labels: bug

#3076 fix granting admin rights
  src/js/components/Shares/ShareItem.vue
Labels: bug

#3079 fix exports
  src/js/Api/modules/activity.js
  src/js/Api/modules/appSettings.js
  src/js/Api/modules/calendar.js
  src/js/Api/modules/comments.js
  src/js/Api/modules/options.js
  src/js/Api/modules/polls.js
  src/js/Api/modules/public.js
  src/js/Api/modules/shares.js
  src/js/Api/modules/userSettings.js
  src/js/Api/modules/validators.js
  src/js/Api/modules/votes.js
  src/js/components/Activity/ActivityItem.vue
  src/js/components/Poll/PublicRegisterModal.vue
  src/js/components/User/UserMenu.vue
  src/js/helpers/index.js
  src/js/helpers/modules/GuestBubble.js
  src/js/helpers/modules/SimpleLink.js
  src/js/helpers/modules/arrayHelper.js
  src/js/helpers/modules/cookieHelper.js
  src/js/router.js
  src/js/store/modules/combo.js
  src/js/store/modules/poll.js
Labels: bug, refactor

#3086 Minor design improvements and hint for unpublished polls
  src/js/App.vue
  src/js/components/Options/Counter.vue
  src/js/components/Options/OptionItem.vue
  src/js/components/Poll/PollInfoLine.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/views/SideBar.vue
  src/js/views/Vote.vue
Labels: enhancement, design, UX

#3087 move template for settings into base component
  src/js/components/Base/index.js
  src/js/components/Base/modules/FlexSettings.vue
  src/js/views/AdminSettingsPage.vue
  src/js/views/UserSettingsPage.vue
Labels: refactor

#3091 improve validatePublicUsername() performance
  lib/Service/SystemService.php
Labels: enhancement
