Repository nextcloud/polls, pull requests merged in 2023-11, with the labels that each got.

#3138 Support Nextcloud 28 and @nextcloud/vue@8
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
Labels: dependencies

#3137 Use info type for some cards
  src/js/components/Actions/modules/ActionSendConfirmed.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/views/Vote.vue
Labels: enhancement

#3140 update to nextcloud-vue beta10
  package-lock.json
  package.json
Labels: dependencies

#3151 use attributes instead of annotations
  lib/Controller/AdminController.php
  lib/Controller/BaseApiController.php
  lib/Controller/BaseController.php
  lib/Controller/CommentApiController.php
  lib/Controller/CommentController.php
  lib/Controller/OptionApiController.php
  lib/Controller/OptionController.php
  lib/Controller/PageController.php
  lib/Controller/PollApiController.php
  lib/Controller/PollController.php
  lib/Controller/PreferencesController.php
  lib/Controller/PublicController.php
  lib/Controller/SettingsController.php
  lib/Controller/ShareApiController.php
  lib/Controller/ShareController.php
  lib/Controller/SubscriptionApiController.php
  lib/Controller/SubscriptionController.php
  lib/Controller/SystemController.php
  lib/Controller/VoteApiController.php
  lib/Controller/VoteController.php
  lib/Controller/WatchController.php
  psalm-baseline.xml
Labels: refactor

#3148 Not null violation error in migrations
  lib/Migration/TableSchema.php
Labels: bug

#3157 synchronize app version with npm version
  package-lock.json
  package.json
  update-app-version.mjs
Labels: enhancement

#3158 update prettier to 3
  package-lock.json
  package.json
Labels: dependencies
