Repository nextcloud/polls, pull requests merged in 2024-09, with the labels that each got.

#3686 backport #3677
  src/helpers/modules/cookieHelper.ts
Labels: bug

#3676 fix: disable vote option while loading
  lib/Controller/VoteController.php
  lib/Service/OptionService.php
  lib/Service/VoteService.php
  src/js/components/VoteTable/VoteItem.vue
  src/js/store/modules/votes.js
Labels: bug, enhancement, 3. to review

#3694 Avoid expensive index recreation
  CHANGELOG.md
  appinfo/info.xml
  lib/Command/Db/Rebuild.php
  lib/Db/IndexManager.php
  lib/Service/PreferencesService.php
  lib/Service/WatchService.php
Labels: bug, enhancement, backport-request

#3670 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: 3. to review, dependencies, automated

#3706 Fix size of creation box in navigation
  CHANGELOG.md
  src/js/assets/scss/hacks.scss
Labels: bug, UX, backport reminder (next branch)

#3708 fix placeholder for email input
  src/js/components/Public/PublicRegisterModal.vue
Labels: bug

#3716 Convert email and contact shares to external shares on first usage
  lib/Db/Share.php
  lib/Service/ShareService.php
Labels: bug, backport-request

#3714 fix: show edit inputs only for external shares
  lib/Db/Share.php
  lib/Service/ShareService.php
  src/js/components/User/UserMenu.vue
Labels: bug, 3. to review, backport reminder (next branch)

#3720 fix vote limit for public users
  lib/Controller/PublicController.php
Labels: bug

#3722 fix aftermath of #3716
  lib/Db/CommentMapper.php
  lib/Db/OptionMapper.php
  lib/Db/VoteMapper.php
  lib/Service/ShareService.php
Labels: bug, backport-request

#3728 [next] fix: show edit inputs only for external shares
  src/components/User/UserMenu.vue
Labels: bug

#3729 [next] fix placeholder for email input
  src/components/Public/PublicRegisterModal.vue
Labels: bug

#3715 Maintenance
  .php-cs-fixer.dist.php
  Makefile
  composer.json
  composer.lock
  lib/Controller/PublicController.php
  lib/Controller/WatchController.php
  lib/Dashboard/PollWidget.php
  lib/Db/Comment.php
  lib/Db/Log.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/Preferences.php
  lib/Db/PreferencesMapper.php
  lib/Db/QBMapperWithUser.php
  lib/Db/Share.php
  lib/Db/TableManager.php
  lib/Db/UserMapper.php
  lib/Db/Vote.php
  lib/Event/BaseEvent.php
  lib/Exceptions/ShareAlreadyExistsException.php
  lib/Helper/Container.php
  lib/Model/CalendarEvent.php
  lib/Model/Mail/ReminderMail.php
  lib/Model/Settings/AppSettings.php
  lib/Provider/ActivityProvider.php
  lib/Service/CalendarService.php
  lib/Service/LogService.php
  lib/Service/MailService.php
  lib/Service/PollService.php
  lib/Service/ShareService.php
  lib/Service/VoteService.php
  lib/Service/WatchService.php
  lib/UserSession.php
  package-lock.json
  package.json
  src/components/Actions/modules/ActionChangeView.vue
  src/components/Actions/modules/ActionDeleteOrphanedVotes.vue
  src/components/Actions/modules/ActionOpenOptionsSidebar.vue
  src/components/Actions/modules/ActionOpenSharesSidebar.vue
  src/components/Actions/modules/ActionRegister.vue
  src/components/Actions/modules/ActionSendConfirmed.vue
  src/components/Actions/modules/ActionSortOptions.vue
  src/components/Actions/modules/ActionSwitchSafeTable.vue
  src/components/Actions/modules/ActionToggleSidebar.vue
  src/components/Export/ExportPoll.vue
  src/components/Options/OptionCloneDate.vue
  src/components/Options/OptionsDateAdd.vue
  src/components/Options/OptionsTextAddBulk.vue
  src/components/Public/PublicRegisterModal.vue
  src/components/Settings/AdminSettings/AdminJobs.vue
  src/views/Administration.vue
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
  vite.config.js
Labels: dependencies, refactor

#3734 use more contexts in logger statements
  lib/Cron/GroupDeletedJob.php
  lib/Cron/UserDeletedJob.php
  lib/Db/TableManager.php
  lib/Model/Mail/MailBase.php
  lib/Model/User/Contact.php
  lib/Service/MailService.php
  lib/Service/OptionService.php
  lib/Service/ShareService.php
  lib/Service/SystemService.php
Labels: refactor, backport-request
