Repository nextcloud/polls, pull requests merged in 2024-02, with the labels that each got.

#3293 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
Labels: 3. to review, dependencies, automated

#3308 Fix/aftermath
  lib/Controller/BasePublicController.php
  lib/Controller/ShareController.php
  lib/Db/PollMapper.php
  lib/Db/ShareMapper.php
  lib/Db/UserMapper.php
  lib/Model/Acl.php
  lib/Service/SubscriptionService.php
  psalm-baseline.xml
  src/js/components/Configuration/ConfigAutoReminder.vue
  src/js/components/Export/ExportPoll.vue
  src/js/components/Navigation/PollNavigationItems.vue
  src/js/components/Options/OptionsDate.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Options/OptionsTextAddBulk.vue
  src/js/components/Shares/ShareItem.vue
  src/js/components/Shares/SharePublicAdd.vue
  src/js/components/User/UserMenu.vue
  src/js/views/Administration.vue
  src/js/views/PollList.vue
Labels: bug

#3309 remove DBAL deprecations
  lib/Db/TableManager.php
  lib/Migration/TableSchema.php
  lib/Migration/Version050100Date20230515083001.php
  lib/Migration/Version060100Date20240209073304.php
Labels: refactor

#3316 fix DELETE: Option owner or poll id missing
  lib/Model/Acl.php
Labels: bug

#3329 Fix reaccessing poll as internal user with public link
  CHANGELOG.md
  appinfo/routes.php
  lib/Controller/PublicController.php
  lib/Controller/ShareController.php
  lib/Exceptions/ShareAlreadyExistsException.php
  lib/Service/ShareService.php
  lib/Service/SystemService.php
  src/js/Api/modules/public.js
Labels: bug

#3331 Fix WatchService accessing pollId 0
  CHANGELOG.md
  lib/Service/WatchService.php
Labels: bug

#3341 fix username check
  CHANGELOG.md
  src/js/Api/modules/validators.js
Labels: bug

#3340 Partially fix email shares
  CHANGELOG.md
  lib/Model/User/Email.php
  lib/Model/UserBase.php
  src/js/components/User/UserSearch.vue
Labels: bug, dependencies

#3343 fix NcSelect
  CHANGELOG.md
  src/js/components/User/UserSearch.vue
Labels: bug

#3349 Fix updating pollOptionText
  CHANGELOG.md
  lib/Db/Comment.php
  lib/Db/Log.php
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/Poll.php
  lib/Db/Preferences.php
  lib/Db/Share.php
  lib/Db/Subscription.php
  lib/Db/TableManager.php
  lib/Db/Vote.php
  lib/Db/Watch.php
  lib/Service/OptionService.php
  psalm-baseline.xml
  tests/Unit/Db/OptionMapperTest.php
  tests/Unit/Db/VoteMapperTest.php
Labels: bug
