Repository nextcloud/polls, pull requests merged in 2024-11, with the labels that each got.

#3765 [Actions] update versions
  .github/ISSUE_TEMPLATE/BUG_REPORT.yml
  .github/actions/setup-composer/action.yml
  .github/actions/setup-server/action.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  lib/Db/Comment.php
  lib/Db/EntityWithUser.php
  lib/Db/Log.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/Preferences.php
  lib/Db/Share.php
  lib/Db/Subscription.php
  lib/Db/Vote.php
  lib/Db/Watch.php
Labels: enhancement, dependencies, backport-request

#3768 Backport shorten column names from next (878e35b)
  lib/Db/Poll.php
  lib/Db/PollMapper.php
Labels: bug

#3777 Fix user search by email
  lib/Model/UserBase.php
  src/js/components/User/UserSearch.vue
Labels: 3. to review

#3786 small fixes
  lib/Service/SystemService.php
  tests/Unit/Db/OptionMapperTest.php
Labels: backport-request
