Repository nextcloud/polls, pull requests merged in 2024-08, with the labels that each got.

#3642 ci: Add release automation workflow
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#3648 fix : deleted user when email share registers
  src/js/components/Cards/VoteInfoCards.vue
Labels: bug, 3. to review

#3662 chore(release): v7.2.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#3664 fix(ci): artifact path in release automation
  .github/workflows/appstore-build-publish.yml
Labels: 3. to review

#3650 fix: pollId equals 0
  lib/Service/WatchService.php
Labels: bug, 4. to release

#3644 Fixes Round 2
  CHANGELOG.md
  lib/Db/Option.php
  lib/Service/OptionService.php
  src/Types/index.ts
  src/components/Combo/ComboTable.vue
  src/components/Combo/VoteColumn.vue
  src/components/Combo/VoteItem.vue
  src/components/Options/OptionItemOwner.vue
  src/components/Options/OptionsDate.vue
  src/components/Options/OptionsText.vue
  src/components/SideBar/SideBarTabDatePolls.vue
  src/components/User/UserMenu.vue
  src/stores/combo.ts
  src/stores/options.ts
  src/stores/subscription.ts
  src/views/Combo.vue
Labels: bug, Migration

#3677 fix: space in token causes 404 on logout
  src/js/helpers/modules/cookieHelper.js
Labels: bug, 3. to review, backport reminder (next branch)

#3680 Backport/3676/next
  lib/Controller/VoteController.php
  lib/Service/OptionService.php
  lib/Service/VoteService.php
  src/stores/votes.ts
Labels: bug, enhancement

#3681 Dep/next/updates
  composer.lock
  lib/Command/Share/Add.php
  lib/Command/Share/Remove.php
  lib/Db/EntityWithUser.php
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/Preferences.php
  lib/Db/PreferencesMapper.php
  lib/Db/Share.php
  lib/Db/ShareMapper.php
  lib/Db/SubscriptionMapper.php
  lib/Db/TableManager.php
  lib/Db/UserMapper.php
  lib/Db/Watch.php
  lib/Db/WatchMapper.php
  lib/Event/BaseEvent.php
  lib/Exceptions/UserNotFoundException.php
  lib/Model/CalendarEvent.php
  lib/Model/Mail/MailBase.php
  lib/Model/Mail/ReminderMail.php
  lib/Model/User/Contact.php
  lib/Model/User/User.php
  lib/Service/MailService.php
  lib/Service/PreferencesService.php
  lib/Service/ShareService.php
  lib/UserSession.php
  package-lock.json
  package.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: dependencies
