Repository nextcloud/polls, pull requests merged in 2024-07, with the labels that each got.

#3602 fix: Display circle share activities correctly
  src/js/components/Activity/ActivityItem.vue
Labels: bug, backport reminder

#3603 fix: strip illegal colon from sheet name
  src/js/components/Export/ExportPoll.vue
Labels: bug, backport-request

#3608 fix: Catch exceptions thrown by NotificationMail constructor
  lib/Service/MailService.php
Labels: bug, 3. to review, backport-request

#3610 chore: update workflows from templates
  .github/workflows/pr-feedback.yml
  .github/workflows/reuse.yml
Labels: dependencies, automated

#3615 Migrate REUSE to toml format
  .reuse/dep5
  REUSE.toml
Labels: 3. text review
