Repository nextcloud/polls, pull requests merged in 2024-04, with the labels that each got.

#3415 bring back archive, restore and delete actions
  CHANGELOG.md
  src/js/components/Navigation/PollNavigationItems.vue
  src/js/views/PollList.vue
Labels: bug

#3419 extract keys insted of wrong usage of key()
  CHANGELOG.md
  lib/Model/Group/Group.php
Labels: bug

#3418 catch error on requesting votes of non existing poll
  CHANGELOG.md
  lib/Service/CommentService.php
  lib/Service/OptionService.php
  lib/Service/SubscriptionService.php
  lib/Service/VoteService.php
Labels: bug

#3421 add common indices
  lib/Command/Db/Rebuild.php
  lib/Command/Db/RemoveIndices.php
  lib/Db/IndexManager.php
  lib/Migration/TableSchema.php
Labels: enhancement

#3428 use bamarni/composer-bin-plugin instead of global tools (stable-5)
  .github/workflows/lint.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  .gitignore
  Makefile
  appinfo/routes.php
  composer.json
  composer.lock
  lib/Command/Command.php
  lib/Command/Poll/TransferOwnership.php
  lib/Controller/CommentApiController.php
  lib/Helper/Container.php
  lib/Model/Acl.php
  lib/Model/CalendarEvent.php
  lib/Service/MailService.php
  lib/Service/ShareService.php
  psalm-baseline.xml
  src/js/App.vue
  src/js/components/Combo/VoteColumn.vue
  src/js/components/Configuration/ConfigProposals.vue
  src/js/components/Create/CreateDlg.vue
  src/js/components/Export/ExportPoll.vue
  src/js/components/Options/OptionProposals.vue
  src/js/components/Options/OptionsDate.vue
  src/js/components/Options/OptionsDateShift.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Poll/PollInfoLine.vue
  src/js/components/Poll/PollInformation.vue
  src/js/components/Public/PublicRegisterModal.vue
  src/js/components/Shares/SharesList.vue
  src/js/components/Shares/SharesListLocked.vue
  src/js/components/Shares/SharesListUnsent.vue
  src/js/components/SideBar/SideBarTabActivity.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/VoteTable/VoteColumn.vue
  src/js/views/SideBar.vue
  src/js/views/SideBarCombo.vue
  src/js/views/Vote.vue
  vendor-bin/php-cs-fixer/composer.json
  vendor-bin/php-cs-fixer/composer.lock
  vendor-bin/phpunit/composer.json
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.json
  vendor-bin/psalm/composer.lock
Labels: enhancement, dependencies

#3445 Perf improvements for stable-6 for 26 branch
  lib/Db/UserMapper.php
  lib/Model/Acl.php
  lib/Service/PollService.php
Labels: 3. to review

#3448 [stable6] fix: Add visual loading feedback for polls list
  src/js/store/modules/polls.js
  src/js/views/PollList.vue
Labels: 3. text review

#3450 Default to "My polls" view
  src/js/router.js
Labels: 4. to release, javascript

#3444 fix: Add visual loading feedback for polls list
  src/js/store/modules/polls.js
  src/js/views/PollList.vue
Labels: bug, 3. to review, UX

#3455 Improve API documentation
  docs/API_v1.0.md
Labels: enhancement

#3456 Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3458 refactoring of polls list with leaner flexbox
  src/js/assets/scss/transitions.scss
  src/js/components/Base/modules/BadgeDiv.vue
  src/js/components/Poll/PollInformation.vue
  src/js/components/PollList/PollItem.vue
  src/js/views/Administration.vue
  src/js/views/Navigation.vue
  src/js/views/PollList.vue
Labels: design, refactor

#3461 Allow to remove the poll list from the navigation by admin setting
  lib/Model/Settings/AppSettings.php
  lib/Service/SettingsService.php
  src/js/components/Settings/AdminSettings/AdminPollsInNavigation.vue
  src/js/store/modules/appSettings.js
  src/js/views/AdminSettingsPage.vue
  src/js/views/Navigation.vue
Labels: enhancement, Performance

#3431 [stable6] Backport of stable 6 for Nextcloud 26
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Controller/AdminController.php
  lib/Controller/BaseApiController.php
  lib/Controller/BaseController.php
  lib/Controller/BasePublicController.php
  lib/Controller/CommentApiController.php
  lib/Controller/CommentController.php
  lib/Controller/OptionApiController.php
  lib/Controller/OptionController.php
  lib/Controller/PageController.php
  lib/Controller/PollApiController.php
  lib/Controller/PollController.php
  lib/Controller/PreferencesController.php
  lib/Controller/PublicController.php
  lib/Controller/SettingsController.php
  lib/Controller/ShareApiController.php
  lib/Controller/ShareController.php
  lib/Controller/SubscriptionApiController.php
  lib/Controller/SubscriptionController.php
  lib/Controller/SystemController.php
  lib/Controller/VoteApiController.php
  lib/Controller/VoteController.php
  lib/Controller/WatchController.php
  lib/Cron/JanitorCron.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/Share.php
  lib/Db/TableManager.php
  lib/Db/UserMapper.php
  lib/Db/VoteMapper.php
  lib/Helper/Container.php
  lib/Middleware/RequestAttributesMiddleware.php
  lib/Migration/TableSchema.php
  lib/Migration/Version060100Date20240209073304.php
  lib/Model/Acl.php
  lib/Model/Settings/AppSettings.php
  lib/Model/UserBase.php
  lib/Service/PollService.php
  lib/Service/SettingsService.php
  lib/Service/WatchService.php
  src/js/store/modules/polls.js
  src/js/views/PollList.vue
  tests/Unit/Db/CommentMapperTest.php
  tests/Unit/Db/LogMapperTest.php
  tests/Unit/Db/OptionMapperTest.php
  tests/Unit/Db/PollMapperTest.php
  tests/Unit/Db/SubscriptionMapperTest.php
  tests/Unit/Db/VoteMapperTest.php
Labels: 4. to release, Performance
