Repository nextcloud/polls, pull requests merged in 2024-06, with the labels that each got.

#3541 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#3552 Fix opening and closing of sidebar
  CHANGELOG.md
  src/js/components/Base/modules/HeaderBar.vue
  src/js/components/Poll/PollHeaderButtons.vue
  src/js/views/SideBar.vue
  src/js/views/SideBarCombo.vue
Labels: bug

#3555 Add missing SPDX header
  appinfo/info.xml.license
  psalm-baseline.xml.license
Labels: bug

#3553 Support NC27
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
  CHANGELOG.md
  appinfo/info.xml
  composer.json
  lib/Db/TableManager.php
  lib/Migration/TableSchema.php
  lib/Migration/Version060100Date20240209073304.php
Labels: enhancement

#3565 Fix: sidebar archive poll
  src/js/components/SideBar/SideBarTabConfiguration.vue
Labels: 4. to release, refactor

#3576 fix poll download
  src/js/components/Poll/PollHeaderButtons.vue
Labels: bug

#3577 fix owner detection
  src/js/components/Comments/CommentItem.vue
  src/js/components/SideBar/SideBarTabConfiguration.vue
  src/js/components/SideBar/SideBarTabOptions.vue
Labels: bug, backport reminder

#3578 Fix joinGroupShares
  lib/Db/PollMapper.php
Labels: bug

#3581 fix detection of archived polls and fix context menu
  src/js/store/modules/combo.js
  src/js/views/Administration.vue
  src/js/views/PollList.vue
Labels: bug

#3595 allow cron user to see more user details
  lib/AppConstants.php
  lib/Cron/AutoReminderCron.php
  lib/Cron/GroupDeletedJob.php
  lib/Cron/JanitorCron.php
  lib/Cron/NotificationCron.php
  lib/Cron/UserDeletedJob.php
  lib/Model/User/Cron.php
  lib/Model/UserBase.php
  lib/Service/MailService.php
  lib/UserSession.php
Labels: bug, backport reminder

#3597 Backport #3565: Fix: sidebar archive poll
  src/components/SideBar/SideBarTabConfiguration.vue
Labels: refactor
