Repository nextcloud/polls, pull requests merged in 2024-05, with the labels that each got.

#3479 Enable chunk loading polls in list and limit polls in navigation.
  src/js/components/Base/index.js
  src/js/components/Base/modules/IntersectionObserver.vue
  src/js/store/modules/polls.js
  src/js/views/Navigation.vue
  src/js/views/PollList.vue
Labels: enhancement, UX, Performance

#3482 change ESLint config to work with prettier
  .eslintrc.js
  .prettierignore
  .prettierrc.json
  package-lock.json
  package.json
Labels: dependencies

#3481 Aftermath: Fixing type error
  src/js/mixins/adminSettingsMixin.js
Labels: bug

#3492 Backport of chunked loading and leaner pollItems
  appinfo/info.xml
  package-lock.json
  package.json
  src/js/assets/scss/transitions.scss
  src/js/components/Base/index.js
  src/js/components/Base/modules/BadgeDiv.vue
  src/js/components/Base/modules/IntersectionObserver.vue
  src/js/components/Poll/PollInformation.vue
  src/js/components/PollList/PollItem.vue
  src/js/store/modules/polls.js
  src/js/views/Dashboard.vue
  src/js/views/Navigation.vue
  src/js/views/PollList.vue
Labels: enhancement, Performance

#3487 Switch from webpack to vite
  .eslintrc.cjs
  Makefile
  appinfo/info.xml
  babel.config.js
  package-lock.json
  package.json
  src/js/adminSettings.js
  src/js/assets/icons/loading-small.gif
  src/js/components/VoteTable/VoteIndicator.vue
  src/js/dashboard.js
  src/js/main.js
  src/js/store/modules/index.js
  src/js/userSettings.js
  src/js/views/Dashboard.vue
  stylelint.config.cjs
  stylelint.config.js
  vite.config.js
Labels: dependencies

#3480 [stable-6] Count user's votes by subquery
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/VoteMapper.php
Labels: 3. to review

#3509 fix attributes namespace
  lib/Attributes/ShareTokenRequired.php
  lib/Controller/PublicController.php
  lib/Middleware/RequestAttributesMiddleware.php
Labels: bug

#3521 do not send autoreminders for archived polls
  lib/Db/PollMapper.php
Labels: bug

#3520 Disable buttons after click
  .github/workflows/codeql-analysis.yml
  src/js/components/Public/PublicRegisterModal.vue
  src/js/components/Shares/ShareItem.vue
Labels: enhancement, UX

#3523 Fix/hiden-results-and-limited-votes
  CHANGELOG.md
  lib/Db/Option.php
  lib/Db/OptionMapper.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  src/js/store/modules/poll.js
  src/js/views/Vote.vue
Labels: bug

#3524 fix dashboard
  src/js/adminSettings.js
  src/js/dashboard.js
  src/js/store/store-polls.js
  src/js/userSettings.js
  src/js/views/Dashboard.vue
Labels: bug

#3525 fix closing and tidy
  src/js/components/Base/modules/ConfigBox.vue
  src/js/components/Configuration/ConfigClosing.vue
  src/js/components/VoteTable/VoteColumn.vue
  src/js/components/VoteTable/VoteTable.vue
  src/js/router.js
  src/js/store/modules/acl.js
  src/js/store/modules/appSettings.js
  src/js/store/modules/poll.js
  src/js/views/Dashboard.vue
Labels: bug

#3532 bring back PHP 8.0 - fixes #3530
  .github/workflows/lint.yml
  appinfo/info.xml
  composer.json
  composer.lock
  vendor-bin/php-cs-fixer/composer.lock
  vendor-bin/phpunit/composer.lock
  vendor-bin/psalm/composer.lock
Labels: enhancement

#3527 adding groupBy for PostgreSQL
  appinfo/info.xml
  lib/Db/CommentMapper.php
  lib/Db/OptionMapper.php
  lib/Db/PollMapper.php
  lib/Db/QBMapperWithUser.php
  lib/Db/ShareMapper.php
  lib/Db/VoteMapper.php
  package-lock.json
  package.json
Labels: bug

#3536 switch back to $emptyString
  lib/Db/PollMapper.php
Labels: bug

#3538 Fix poll list content
  lib/Service/PollService.php
  src/js/components/Configuration/ConfigAutoReminder.vue
  src/js/components/Export/ExportPoll.vue
  src/js/components/Navigation/PollNavigationItems.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Options/OptionsTextAddBulk.vue
  src/js/components/Shares/ShareItem.vue
  src/js/components/Shares/SharePublicAdd.vue
  src/js/components/User/UserMenu.vue
  src/js/store/modules/polls.js
  src/js/views/Administration.vue
  src/js/views/Dashboard.vue
  src/js/views/Navigation.vue
  src/js/views/PollList.vue
Labels: bug
