Repository nextcloud/polls, pull requests merged in 2025-08, with the labels that each got.

#4197 Loading optimizations
  lib/Db/PollGroupMapper.php
  lib/Db/PollMapper.php
  src/components/Configuration/ConfigDangerArea.vue
  src/components/PollGroup/PollGroupEditDlg.vue
  src/components/PollList/PollItemActions.vue
  src/components/SideBar/SideBarTabComments.vue
  src/components/SideBar/SideBarTabShare.vue
  src/composables/usePollWatcher.ts
  src/composables/usePollWatcher.types.ts
  src/router.ts
  src/stores/appSettings.types.ts
  src/stores/poll.ts
  src/stores/pollGroups.ts
  src/stores/session.types.ts
  src/stores/subscription.ts
  src/views/SideBar.vue
  src/views/Vote.vue
  src/workers/pollWatcher.worker.ts
Labels: bugfix, refactor

#4201 keyed children of vote-table
  src/components/VoteTable/VoteTable.vue
Labels: bugfix

#4205 move description to StickyDiv
  CHANGELOG.md
  src/views/Vote.vue
Labels: bugfix

#4219 fix vote limitations
  lib/Db/PollMapper.php
  src/components/VoteTable/VoteTable.vue
  src/stores/votes.ts
Labels: bugfix

#4220 Move comments config to comment tab
  CHANGELOG.md
  lib/Db/Poll.php
  src/components/Configuration/AutoReminderInformation.vue
  src/components/Configuration/ConfigAutoReminder.vue
  src/components/SideBar/SideBarTabComments.vue
  src/components/SideBar/SideBarTabConfiguration.vue
  src/components/VoteTable/VoteTable.vue
Labels: enhancement

#4235 move table cleaning to postMigration
  CHANGELOG.md
  lib/Db/V3/TableManager.php
  lib/Migration/Version080307Date20250826231102.php
Labels: bugfix

#4236 fix: show full username on hover
  src/components/User/UserItem.vue
Labels: bugfix, backport-request

#4257 Migrate calendar keys to URI for calendarcheck
  lib/Controller/UserController.php
  lib/Db/Preferences.php
  lib/Service/CalendarService.php
  lib/Service/PreferencesService.php
  src/components/Settings/UserSettings/CalendarSettings.vue
  src/stores/preferences.ts
  src/stores/preferences.types.ts
Labels: bugfix
