Repository nextcloud/polls, pull requests merged in 2025-02, with the labels that each got.

#3869 Fix transfer of polls via occ
  .gitignore
  lib/UserSession.php
Labels: bug, backport-request

#3877 fix takeover and delete polls in admin list
  src/views/Administration.vue
Labels: bug

#3878 fix: Remove dropdown options limit from sharing search
  src/js/components/User/UserSearch.vue
Labels: enhancement, 4. to release

#3882 [next] fix: Remove dropdown options limit from sharing search
  src/components/User/UserSearch.vue
Labels: enhancement

#3883 add nightly parameter
  .github/workflows/appstore-build-publish.yml
Labels: bug, backport-request
