Repository nextcloud/polls, pull requests merged in 2025-06, with the labels that each got.

#4076 introduce confidential comments
  CHANGELOG.md
  lib/Controller/CommentController.php
  lib/Db/Comment.php
  lib/Db/CommentMapper.php
  lib/Db/Poll.php
  lib/Migration/TableSchema.php
  lib/Migration/Version080000Date20250604195002.php
  lib/Service/CommentService.php
  src/Api/modules/comments.ts
  src/Api/modules/public.ts
  src/components/Comments/CommentAdd.vue
  src/components/Comments/CommentItem.vue
  src/components/Configuration/ConfigForceConfidentialComments.vue
  src/components/SideBar/SideBarTabConfiguration.vue
  src/stores/comments.ts
  src/stores/poll.ts
Labels: enhancement

#4081 catch missing user for system jobs
  lib/Db/UserMapper.php
  lib/UserSession.php
Labels: bug

#4086 Avoid broken updates on invalid vote records
  appinfo/info.xml
  lib/Db/TableManager.php
Labels: bug, backport-request

#4088 Fixes and enhancements round 7678
  src/components/Actions/modules/ActionSendConfirmed.vue
  src/components/Base/modules/CardDiv.vue
  src/components/Cards/VoteInfoCards.vue
  src/components/Cards/modules/CardLimitedVotes.vue
  src/components/Configuration/ConfigOptionLimit.vue
  src/components/Poll/MarkDownDescription.vue
  src/components/Subscription/Subscription.vue
  src/helpers/modules/StoreHelper.ts
  src/main.ts
  src/polls-reference.ts
  src/stores/options.ts
  src/views/Reference.vue
  src/views/Vote.vue
  templates/main.php
Labels: bug, enhancement

#4105 poll overview for groups
  lib/Controller/PageController.php
  lib/Db/PollGroup.php
  src/router.ts
  src/stores/polls.ts
  src/stores/session.ts
  src/views/Navigation.vue
  src/views/PollList.vue
Labels: enhancement

#4106 Edit poll groups
  lib/Controller/PollController.php
  lib/Service/PollService.php
  src/Api/modules/polls.ts
  src/components/Actions/modules/ActionEditGroup.vue
  src/components/PollGroup/PollGroupEditDlg.vue
  src/stores/polls.ts
  src/views/PollList.vue
Labels: enhancement

#4112 fix display of list-view
  src/components/VoteTable/VoteTable.vue
Labels: bug

#4118 fix activity stream
  lib/Provider/ActivityProvider.php
Labels: bug

#4117 some design and css isues, opmizations
  .gitignore
  src/App.vue
  src/assets/scss/vars.scss
  src/components/VoteTable/VoteTable.vue
  src/views/Vote.vue
Labels: bug, design

#4121 pause watcher, if tab is in background
  CHANGELOG.md
  src/composables/usePollWatcher.ts
Labels: enhancement

#4133 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#4139 fix(l10n): apply translation guidelines
  lib/Notification/Notifier.php
  lib/Service/ActivityService.php
  src/components/Cards/modules/CardAddProposals.vue
  src/components/User/UserSearch.vue
Labels: backport-request
