Repository nextcloud/polls, pull requests merged in 2025-03, with the labels that each got.

#3894 Apply core share group restrictions
  lib/Model/Acl.php
  lib/Model/Settings/AppSettings.php
  lib/Model/User/User.php
  lib/Model/UserBase.php
  lib/Service/ShareService.php
  lib/Service/SystemService.php
  src/js/components/Shares/SharesList.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/store/modules/acl.js
Labels: enhancement, backport-request

#3901 [next] Apply core share group restrictions
  lib/AppInfo/Application.php
  lib/Dashboard/PollWidget.php
  lib/Db/CommentMapper.php
  lib/Db/IndexManager.php
  lib/Db/LogMapper.php
  lib/Db/Option.php
  lib/Db/Poll.php
  lib/Db/PollMapper.php
  lib/Db/PreferencesMapper.php
  lib/Db/ShareMapper.php
  lib/Db/SubscriptionMapper.php
  lib/Db/TableManager.php
  lib/Db/UserMapper.php
  lib/Db/VoteMapper.php
  lib/Db/WatchMapper.php
  lib/Event/PollExpiredEvent.php
  lib/Listener/BaseListener.php
  lib/Middleware/RequestAttributesMiddleware.php
  lib/Model/CalendarEvent.php
  lib/Model/SentResult.php
  lib/Model/Settings/AppSettings.php
  lib/Model/Settings/SystemSettings.php
  lib/Model/User/Email.php
  lib/Model/UserBase.php
  lib/Notification/Notifier.php
  lib/Provider/SearchProvider.php
  lib/Service/ActivityService.php
  lib/Service/CalendarService.php
  lib/Service/CommentService.php
  lib/Service/LogService.php
  lib/Service/MailService.php
  lib/Service/NotificationService.php
  lib/Service/OptionService.php
  lib/Service/PollService.php
  lib/Service/PreferencesService.php
  lib/Service/SettingsService.php
  lib/Service/ShareService.php
  lib/Service/SubscriptionService.php
  lib/Service/SystemService.php
  lib/Service/VoteService.php
  lib/Service/WatchService.php
  lib/Settings/ActivitySettings.php
  lib/UserSession.php
  src/Types/index.ts
  src/components/Shares/SharesList.vue
  src/components/SideBar/SideBarTabShare.vue
  src/stores/poll.ts
  src/stores/session.ts
Labels: enhancement

#3903 update alternative dialog for editing options
  package-lock.json
  package.json
  src/components/Actions/modules/ActionRegister.vue
  src/components/Base/modules/DateTimePicker.vue
  src/components/Modals/OptionsAddModal.vue
  src/components/Options/OptionCloneDate.vue
  src/components/Options/OptionsDateAddDialog.vue
  src/components/Options/OptionsDateAddDialog_origin.vue
  src/components/Options/OptionsDateShift.vue
  src/components/Poll/PollInformation.vue
  src/constants/dateUnits.ts
  src/stores/options.ts
Labels: enhancement

#3907 fix preferences === null
  lib/Controller/UserController.php
  lib/Service/PreferencesService.php
Labels: bug

#3908 cast activity rich object paramaters to string
  lib/Db/Share.php
  lib/Event/BaseEvent.php
  lib/Event/CommentEvent.php
  lib/Event/OptionEvent.php
Labels: bug, enhancement, backport-request

#3911 reactivate in app activities
  src/components/Activity/ActivityItem.vue
  src/components/SideBar/SideBarTabActivity.vue
  src/stores/poll.ts
Labels: bug, enhancement

#3912 fix dashboard links
  src/views/Dashboard.vue
Labels: bug

#3913 Changes to user menu
  src/components/User/UserMenu.vue
  src/stores/options.ts
  src/stores/poll.ts
Labels: enhancement

#3922 fix ocs api routes
  lib/Controller/CommentApiController.php
  lib/Controller/OptionApiController.php
  lib/Controller/PollApiController.php
  lib/Controller/ShareApiController.php
  lib/Controller/SubscriptionApiController.php
  lib/Controller/UserApiController.php
  lib/Controller/VoteApiController.php
Labels: bug

#3925 keep Container abstraction
  lib/Controller/PollController.php
  lib/Cron/JanitorCron.php
  lib/Db/EntityWithUser.php
  lib/Db/Share.php
  lib/Helper/Container.php
  lib/Model/UserBase.php
Labels: refactor

#3927 Rework of the polls list
  lib/Db/Poll.php
  lib/Model/UserBase.php
  lib/Service/PollService.php
  src/Types/index.ts
  src/components/Base/modules/BadgeSmallDiv.vue
  src/components/Configuration/ConfigAnonymous.vue
  src/components/PollList/PollItem.vue
  src/components/PollList/PollItemActions.vue
  src/components/PollList/PollListSort.vue
  src/router.ts
  src/stores/polls.ts
  src/stores/pollsAdmin.ts
  src/views/Administration.vue
  src/views/Navigation.vue
  src/views/PollList.vue
Labels: enhancement, refactor

#3932 changed to master-*
  .github/workflows/codeql-analysis.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  .github/workflows/phpunit.yml
  .github/workflows/static-analysis.yml
Labels: dependencies

#3928 fix: list polls after taking over
  src/js/store/modules/pollsAdmin.js
Labels: bug, 3. to review, backport reminder (next branch)

#3938 fix: html and excel exports
  lib/Db/Vote.php
  src/js/components/Export/ExportPoll.vue
  src/js/store/modules/votes.js
Labels: bug, 3. to review, backport reminder (main branch)

#3943 fix access check
  lib/Service/PollService.php
Labels: bug, backport-request
