Repository nextcloud/polls, pull requests merged in 2025-05, with the labels that each got.

#3993 Fix typo "unexecuteted"
  README.md
Labels: backport-request

#3997 Make description collapsible
  lib/Db/Preferences.php
  src/App.vue
  src/components/Base/index.ts
  src/components/Base/modules/Collapsible.vue
  src/components/Base/modules/HeaderBar.vue
  src/components/Poll/MarkUpDescription.vue
  src/components/Settings/UserSettings/StyleSettings.vue
  src/stores/preferences.ts
  src/views/Vote.vue
Labels: enhancement

#4018 Fixing psalm hints
  composer.json
  lib/Controller/BaseApiV2Controller.php
  lib/Controller/BaseController.php
  lib/Controller/SystemController.php
  lib/Exceptions/DuplicateEntryException.php
  lib/Model/Settings/SystemSettings.php
  lib/Service/MailService.php
  lib/Service/OptionService.php
  lib/Service/PollService.php
  lib/Service/SystemService.php
  lib/Types.php
  psalm-baseline.xml
  psalm.xml
  stubs/circles-stubs.php
Labels: Maintenance

#4023 Bump @nextcloud/vue from 9.0.0-alpha.8 to 9.0.0-rc.1
  package-lock.json
  src/components/Actions/modules/ActionAddOption.vue
  src/components/Actions/modules/ActionAddPoll.vue
  src/components/Actions/modules/ActionDelete.vue
  src/components/Actions/modules/ActionDeleteOrphanedVotes.vue
  src/components/Actions/modules/ActionOpenOptionsSidebar.vue
  src/components/Actions/modules/ActionOpenSharesSidebar.vue
  src/components/Actions/modules/ActionRegister.vue
  src/components/Actions/modules/ActionSendConfirmed.vue
  src/components/Actions/modules/ActionSwitchSafeTable.vue
  src/components/Actions/modules/ActionToggleSidebar.vue
  src/components/Base/modules/ButtonModal.vue
  src/components/Base/modules/DateTimePicker.vue
  src/components/Base/modules/InputDiv.vue
  src/components/Configuration/ConfigAnonymous.vue
  src/components/Configuration/ConfigDangerArea.vue
  src/components/Create/CreateDlg.vue
  src/components/Create/PollCreateDlg.vue
  src/components/Modals/DeletePollDialog.vue
  src/components/Modals/TransferPollDialog.vue
  src/components/Options/OptionCloneDate.vue
  src/components/Options/OptionsDateAddDialog.vue
  src/components/Options/OptionsDateShift.vue
  src/components/Options/OptionsTextAddBulk.vue
  src/components/Poll/MarkUpDescription.vue
  src/components/Poll/PollHeaderButtons.vue
  src/components/PollList/PollItemActions.vue
  src/components/Public/PublicRegisterModal.vue
  src/components/Settings/AdminSettings/AdminJobs.vue
  src/components/Shares/SharesListUnsent.vue
  src/components/VoteTable/VoteParticipant.vue
  src/components/VoteTable/VoteTable.vue
  src/stores/appSettings.ts
  src/stores/session.ts
Labels: dependencies, javascript

#4024 some code tidy
  src/components/Actions/modules/ActionAddOption.vue
  src/components/Actions/modules/ActionAddPoll.vue
  src/components/Actions/modules/ActionDelete.vue
  src/components/AppIcons/modules/MaybeIcon.vue
  src/components/AppIcons/modules/PollsAppIcon.vue
  src/components/AppIcons/modules/Spinner.vue
  src/components/AppIcons/modules/types.ts
  src/components/Base/modules/BadgeDiv.vue
  src/components/Base/modules/BadgeSmallDiv.vue
  src/components/Base/modules/ButtonModal.vue
  src/components/Base/modules/Collapsible.vue
  src/components/Base/modules/ConfigBox.vue
  src/components/Base/modules/DateBox.vue
  src/components/Base/modules/DateTimePicker.vue
  src/components/Base/modules/FlexSpacer.vue
  src/components/Base/modules/InputDiv.vue
  src/components/Base/modules/QrModal.vue
  src/components/Base/modules/RadioGroupDiv.vue
  src/components/Calendar/CalendarInfo.vue
  src/components/Calendar/CalendarPeek.vue
  src/components/Combo/ComboTable.vue
  src/components/Combo/VoteColumn.vue
  src/components/Combo/VoteItem.vue
  src/components/Comments/CommentItem.vue
  src/components/Modals/DeletePollDialog.vue
  src/components/Modals/TransferPollDialog.vue
  src/components/Navigation/PollNavigationItems.vue
  src/components/Options/Counter.vue
  src/components/Options/OptionCloneDate.vue
  src/components/Options/OptionItem.vue
  src/components/Options/OptionItemDateBox.vue
  src/components/Options/OptionItemOwner.vue
  src/components/Options/OptionMenu.vue
  src/components/Options/OptionsDateAddDialog.vue
  src/components/Options/OptionsTextAdd.vue
  src/components/Options/OptionsTextAddBulk.vue
  src/components/PollList/PollItem.vue
  src/components/PollList/PollItemActions.vue
  src/components/Shares/ShareItem.vue
  src/components/User/UserItem.vue
  src/components/User/UserMenu.vue
  src/components/User/UserSearch.vue
  src/components/VoteTable/VoteColumn.vue
  src/components/VoteTable/VoteIndicator.vue
  src/components/VoteTable/VoteItem.vue
  src/components/VoteTable/VoteMenu.vue
  src/components/VoteTable/VoteParticipant.vue
Labels: refactor

#4025 update @nextcloud/dialogs to 7.0.0-rc.0
  package-lock.json
  package.json
Labels: dependencies

#4026 Redesign Watcher as Webworker
  .gitignore
  lib/Controller/PublicController.php
  lib/Db/Watch.php
  lib/Service/WatchService.php
  package-lock.json
  package.json
  src/Api/modules/HttpApi.js
  src/Api/modules/polls.ts
  src/Api/modules/public.ts
  src/App.vue
  src/composables/context.ts
  src/composables/usePollWatcher.ts
  src/composables/usePollWatcher.types.ts
  src/composables/watchPolls.js
  src/stores/session.ts
  src/workers/pollWatcher.worker.ts
  sync_list.txt
Labels: enhancement

#4031 implement reference provider
  CHANGELOG.md
  img/polls.svg
  lib/AppInfo/Application.php
  lib/Reference/PollReferenceProvider.php
  lib/Service/PollService.php
Labels: enhancement

#4033 Use different formatted language code for luxon
  lib/Model/UserBase.php
  src/Types/index.ts
  src/components/Base/modules/DateBox.vue
  src/components/Export/ExportPoll.vue
  src/components/Options/OptionItemDateBox.vue
  src/components/Options/OptionsDateAddDialog.vue
Labels: bug

#4036 Introduce reference link and picker
  CHANGELOG.md
  lib/AppInfo/Application.php
  lib/Listener/PollsReferenceListener.php
  lib/Provider/ReferenceProvider.php
  lib/Provider/SearchProvider.php
  src/components/PollList/PollItem.vue
  src/polls-reference.ts
  src/views/Reference.vue
  vite.config.js
Labels: enhancement

#4037 fix email condition for public shares
  CHANGELOG.md
  package-lock.json
  src/js/App.vue
  src/js/assets/scss/hacks.scss
  src/js/assets/scss/print.scss
  src/js/components/Activity/ActivityItem.vue
  src/js/components/Base/modules/CardDiv.vue
  src/js/components/Base/modules/ConfigBox.vue
  src/js/components/Base/modules/FlexSettings.vue
  src/js/components/Base/modules/HeaderBar.vue
  src/js/components/Base/modules/InputDiv.vue
  src/js/components/Base/modules/LoadingOverlay.vue
  src/js/components/Calendar/CalendarInfo.vue
  src/js/components/Combo/VoteColumn.vue
  src/js/components/Comments/CommentAdd.vue
  src/js/components/Comments/CommentItem.vue
  src/js/components/Configuration/ConfigAutoReminder.vue
  src/js/components/Options/OptionItem.vue
  src/js/components/Options/OptionsText.vue
  src/js/components/Options/OptionsTextAdd.vue
  src/js/components/Options/OptionsTextAddBulk.vue
  src/js/components/PollList/PollItem.vue
  src/js/components/Public/PublicRegisterModal.vue
  src/js/components/Settings/AdminSettings/AdminEmail.vue
  src/js/components/Shares/ShareItem.vue
  src/js/components/SideBar/SideBarTabOptions.vue
  src/js/components/SideBar/SideBarTabShare.vue
  src/js/components/User/UserItem.vue
  src/js/components/VoteTable/VoteIndicator.vue
  src/js/components/VoteTable/VoteTable.vue
Labels: bug

#4039 reroute user to notfound or login page
  src/router.ts
Labels: bug

#4035 update ocp and remove deprecations
  composer.json
  composer.lock
  lib/Notification/Notifier.php
  lib/Provider/ActivityProvider.php
Labels: refactor

#4050 Misc fixes and tidy (again)
  lib/Controller/PageController.php
  lib/Db/UserMapper.php
  lib/Event/BaseEvent.php
  lib/Notification/Notifier.php
  lib/Service/NotificationService.php
  lib/Settings/ActivityVote.php
  src/components/Poll/PollHeaderButtons.vue
  src/components/User/UserMenu.vue
  src/stores/polls.ts
  src/views/Navigation.vue
Labels: enhancement

#4054 Some more optimizations
  .stylelintignore
  package-lock.json
  package.json
  src/App.vue
  src/assets/scss/hacks.scss
  src/assets/scss/print.scss
  src/components/Activity/ActivityItem.vue
  src/components/Base/modules/BadgeSmallDiv.vue
  src/components/Base/modules/CardDiv.vue
  src/components/Base/modules/Collapsible.vue
  src/components/Base/modules/ConfigBox.vue
  src/components/Base/modules/FlexSettings.vue
  src/components/Base/modules/HeaderBar.vue
  src/components/Base/modules/InputDiv.vue
  src/components/Base/modules/LoadingOverlay.vue
  src/components/Calendar/CalendarInfo.vue
  src/components/Combo/VoteColumn.vue
  src/components/Comments/CommentAdd.vue
  src/components/Comments/CommentItem.vue
  src/components/Configuration/ConfigAutoReminder.vue
  src/components/Options/OptionItem.vue
  src/components/Options/OptionsDateAddDialog.vue
  src/components/Options/OptionsText.vue
  src/components/Options/OptionsTextAdd.vue
  src/components/Options/OptionsTextAddBulk.vue
  src/components/PollList/PollItem.vue
  src/components/Public/PublicRegisterModal.vue
  src/components/Settings/AdminSettings/AdminEmail.vue
  src/components/Shares/ShareItem.vue
  src/components/SideBar/SideBarTabShare.vue
  src/components/User/UserItem.vue
  src/components/VoteTable/VoteTable.vue
  src/main.ts
  src/views/Navigation.vue
  src/views/Reference.vue
  src/views/Vote.vue
Labels: enhancement, refactor
